#!/usr/bin/env python3
"""
Shark Agent - Security Audit via DeepSeek R1
"""
import requests
import json
import os

API_KEY = 'sk-e8e93e31b582423e9fdaa4ab8e9347e2'
MODEL = 'deepseek-reasoner'

# Read setup.sh
with open('/home/leviathan/projects/shark-agent/setup.sh', 'r') as f:
    setup_script = f.read()

# Read install.sh (skill installer)
with open('/home/leviathan/projects/shark-agent/scripts/install.sh', 'r') as f:
    install_skill = f.read()

prompt = f'''You are a security auditor. Analyze these scripts for security vulnerabilities.

## CONTEXT
Shark Agent is a public-facing product. Users run:
  curl -fsSL https://raw.githubusercontent.com/leviathan-devops/shark-agent/main/setup.sh | bash

This should be SAFE for anyone to run. Find ALL security issues.

## SCRIPT 1: setup.sh
{setup_script}

## SCRIPT 2: install-skill.sh
{install_skill}

## AUDIT REQUIREMENTS

Identify ALL security vulnerabilities including:

1. **curl | bash risks** - MITM attacks, repo compromise, DNS hijacking
2. **npm package risks** - Malicious packages, typosquatting, supply chain
3. **API key storage** - Plaintext config, file permissions, exposure
4. **File permissions** - Scripts, config files, skill files
5. **Code injection** - User input, environment variables, path traversal
6. **Supply chain attacks** - GitHub repo compromise, npm dependencies
7. **Privilege escalation** - sudo usage, writable directories
8. **Data leakage** - API keys in logs, process lists, history

## OUTPUT FORMAT

For EACH vulnerability found:

### [VULNERABILITY NAME]
- **Severity:** Critical/High/Medium/Low
- **Location:** File:line or component
- **Description:** What's wrong
- **Exploit Scenario:** How attacker exploits this
- **Fix:** Exact code change required

## ADDITIONAL ANALYSIS

Also provide:
1. Secure alternative patterns
2. Hardening recommendations
3. What's already secure (don't change)
4. Overall security rating (1-10)

Be extremely thorough. This goes to public users.'''

headers = {'Authorization': f'Bearer {API_KEY}', 'Content-Type': 'application/json'}
payload = {'model': MODEL, 'messages': [{'role': 'user', 'content': prompt}], 'max_tokens': 4096}

print('🔒 DeepSeek Brain - Security Audit Started...\n')
print('=' * 70)

try:
    response = requests.post('https://api.deepseek.com/v1/chat/completions', headers=headers, json=payload, timeout=120)
    result = response.json()
    
    if 'choices' in result and len(result['choices']) > 0:
        content = result['choices'][0]['message']['content']
        print(content)
        
        # Save audit to file
        with open('/home/leviathan/projects/shark-agent/SECURITY_AUDIT.md', 'w') as f:
            f.write('# Security Audit Report\n\n')
            f.write('Generated by DeepSeek R1\n\n')
            f.write(content)
        print('\n' + '=' * 70)
        print('✅ Audit saved to SECURITY_AUDIT.md')
    else:
        print(f'❌ API Error: {result}')
except Exception as e:
    print(f'❌ Error: {e}')