/**
 * src/eie/warhead-generator.ts — Warhead Guidance System (T1)
 *
 * Generates 300-600 token T1 injectable .md files for events that need
 * more guidance than the 80-char bullet (T0) can provide.
 *
 * Triple Duty (EIE_DESIGN_SPEC.md §6):
 *   1. THINKING   — Re-align after major events (gate rejection, PSM activation)
 *   2. REMEMBERING — Post-compaction knowledge recovery
 *   3. ORIENTING  — Gate entry orientation
 *
 * Triggers (§6):
 *   - Gate advance rejected → warhead with missing evidence + how to produce it
 *   - PSM activation        → warhead with problem-solving framework
 *   - Enforcement block     → warhead with enforcement guidance
 *   - Gate transition       → gate entry warhead
 *   - CME drift >0.7        → trajectory analysis warhead
 *   - Error encountered     → error recovery warhead (parse, match, inject fix)
 *   - Compaction recovery   → reconstruct knowledge state
 *
 * Warheads are written to .shark/warheads/{timestamp}-{trigger}.md and
 * injected via the messages.transform hook (one-shot: consumed on read).
 *
 * Part of EIE Phase 4 (EIE_DESIGN_SPEC.md §6).
 */

import * as fs from 'fs';
import * as path from 'path';
import type { AgentState, WarheadTrigger, WarheadPurpose, KnowledgeNode } from './types';
import { matchKnowledge, getNodesForGate } from './context-matcher';
import { getProgressiveDisclosure } from './progressive-disclosure';
import { ALL_KNOWLEDGE_NODES } from './nodes';

// ── Constants ────────────────────────────────────────────────────

const WARHEAD_DIR = '.shark/warheads';
const MIN_TOKENS = 300;
const MAX_TOKENS = 600;

/** Standard BPE approximation: ~4 characters per token for English text. */
const CHARS_PER_TOKEN = 4;

const FOOTER = '\n\n---\n_Generated by EIE Warhead Generator_';

// ── Token Estimation ─────────────────────────────────────────────

/**
 * Estimate the token count of a string.
 * Uses the standard chars/4 approximation (OpenAI's rough heuristic).
 */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / CHARS_PER_TOKEN);
}

// ── Public API ───────────────────────────────────────────────────

/**
 * Generate a warhead .md file for the given trigger.
 *
 * Returns the absolute file path of the generated warhead, or null on
 * failure. The content is guaranteed to fall within the 300-600 token
 * range (EIE_DESIGN_SPEC.md §19.3 self-verification check #3).
 *
 * @param trigger       What event activated the warhead
 * @param state         Current agent state (gate, tool, evidence, etc.)
 * @param workspacePath Absolute path to the workspace root
 */
export function generateWarhead(
  trigger: WarheadTrigger,
  state: AgentState,
  workspacePath: string,
): string | null {
  const purpose = determinePurpose(trigger);
  const raw = buildWarheadContent(trigger, state, purpose);

  if (!raw) return null;

  const content = enforceTokenRange(raw, state);

  // Ensure the warhead directory exists
  const warheadDir = path.join(workspacePath, WARHEAD_DIR);
  try {
    if (!fs.existsSync(warheadDir)) {
      fs.mkdirSync(warheadDir, { recursive: true });
    }
  } catch {
    return null;
  }

  const timestamp = Date.now();
  const fileName = `${timestamp}-${trigger.type}.md`;
  const filePath = path.join(warheadDir, fileName);

  try {
    fs.writeFileSync(filePath, content, 'utf-8');
  } catch {
    return null;
  }

  return filePath;
}

/**
 * Get the latest warhead for injection via messages.transform.
 *
 * This is a one-shot read: the file is deleted after reading so it is
 * only injected once. Returns null if no warheads exist.
 */
export function getLatestWarhead(workspacePath: string): string | null {
  const warheadDir = path.join(workspacePath, WARHEAD_DIR);
  if (!fs.existsSync(warheadDir)) return null;

  let files: string[];
  try {
    files = fs
      .readdirSync(warheadDir)
      .filter((f: string) => f.endsWith('.md'))
      .sort()
      .reverse();
  } catch {
    return null;
  }

  if (files.length === 0) return null;

  const filePath = path.join(warheadDir, files[0]);
  const content = fs.readFileSync(filePath, 'utf-8');

  // One-shot injection: delete after reading (force=true suppresses ENOENT)
  fs.rmSync(filePath, { force: true });

  return content;
}

/**
 * Clean expired warheads (older than 5 minutes).
 *
 * Warheads are ephemeral guidance artifacts — if they were not consumed
 * within 5 minutes they are stale and should be removed.
 */
export function cleanExpiredWarheads(workspacePath: string): void {
  const warheadDir = path.join(workspacePath, WARHEAD_DIR);
  if (!fs.existsSync(warheadDir)) return;

  const fiveMinAgo = Date.now() - 5 * 60 * 1000;

  let files: string[];
  try {
    files = fs.readdirSync(warheadDir).filter((f: string) => f.endsWith('.md'));
  } catch {
    return; // Cannot read warhead directory — abort cleanup
  }

  for (const f of files) {
    const timestamp = parseInt(f.split('-')[0], 10);
    if (!Number.isNaN(timestamp) && timestamp < fiveMinAgo) {
      fs.rmSync(path.join(warheadDir, f), { force: true });
    }
  }
}

// ── Purpose Determination ────────────────────────────────────────

/**
 * Map a trigger type to its triple-duty purpose.
 *
 * - orienting  → gate entry (what to do in this gate)
 * - thinking   → re-align after a major event (rejection, error, drift)
 * - remembering → compaction recovery (reconstruct knowledge state)
 */
function determinePurpose(trigger: WarheadTrigger): WarheadPurpose {
  switch (trigger.type) {
    case 'gate-entry':
      return 'orienting';
    case 'gate-rejection':
    case 'psm-activation':
    case 'error-encountered':
    case 'enforcement-block':
    case 'drift-detected':
      return 'thinking';
    case 'compaction-recovery':
      return 'remembering';
    default:
      return 'thinking';
  }
}

// ── Content Building ─────────────────────────────────────────────

/**
 * Dispatch to the appropriate warhead builder based on purpose.
 */
function buildWarheadContent(
  trigger: WarheadTrigger,
  state: AgentState,
  purpose: WarheadPurpose,
): string | null {
  switch (purpose) {
    case 'orienting':
      return buildGateEntryWarhead(trigger.gate || state.gate, state);
    case 'thinking':
      return buildReAlignmentWarhead(trigger, state);
    case 'remembering':
      return buildCompactionRecoveryWarhead(state);
    default:
      return null;
  }
}

// ── Orienting: Gate Entry Warhead ────────────────────────────────

/**
 * Build a gate-entry orientation warhead.
 *
 * Contains: what the gate is for, what evidence is required, what tools
 * to use, what to avoid, and how to advance.
 */
function buildGateEntryWarhead(gate: string, state: AgentState): string {
  const gateUpper = gate.toUpperCase();
  const nodes = getGateNodes(gate);

  const lines: string[] = [];
  lines.push(`# ${gateUpper} Gate Active`);
  lines.push('');
  lines.push(
    `You are now in the **${gateUpper}** gate. ` +
      `This warhead orients you on what this gate requires.`,
  );
  lines.push('');

  // Gate-specific knowledge nodes (the primary guidance)
  const gkNodes = nodes.filter((n) => n.category === 'gate-knowledge');
  if (gkNodes.length > 0) {
    lines.push('## What This Gate Requires');
    for (const n of gkNodes) {
      lines.push(`- **${n.id}**: ${firstSentence(n.rule)}`);
    }
    lines.push('');
  }

  // Block-severity requirements (must satisfy to advance)
  const blockNodes = nodes
    .filter((n) => n.severity === 'block' && n.category !== 'gate-knowledge')
    .slice(0, 5);
  if (blockNodes.length > 0) {
    lines.push('## Critical Requirements');
    for (const n of blockNodes) {
      lines.push(`- ${substituteWarheadTemplate(n.bulletTemplate, state)}`);
    }
    lines.push('');
  }

  // Guide-severity nodes (best practices)
  const guideNodes = nodes.filter((n) => n.severity === 'guide').slice(0, 3);
  if (guideNodes.length > 0) {
    lines.push('## Guidance');
    for (const n of guideNodes) {
      lines.push(`- ${firstSentence(n.rule)}`);
    }
    lines.push('');
  }

  lines.push('## How To Advance');
  lines.push(
    'Produce the required mechanical evidence for this gate, then call ' +
      '`shark-gate advance`.',
  );

  return lines.join('\n') + FOOTER;
}

// ── Thinking: Re-Alignment Warheads ──────────────────────────────

/**
 * Build a re-alignment warhead for thinking purposes.
 *
 * Handles: gate rejection, PSM activation, error recovery, enforcement
 * block, and drift detection. Each branch pulls relevant knowledge
 * nodes from the graph to give the model actionable guidance.
 */
function buildReAlignmentWarhead(trigger: WarheadTrigger, state: AgentState): string {
  const gateUpper = (trigger.gate || state.gate || 'plan').toUpperCase();
  const lines: string[] = [];

  // ── Gate Rejection ───────────────────────────────────────────
  if (trigger.type === 'gate-rejection' && trigger.missingEvidence?.length) {
    lines.push('# Gate Advance Rejected');
    lines.push('');
    lines.push(`Current gate: **${gateUpper}**`);
    lines.push('');
    lines.push('## Missing Evidence');
    for (const ev of trigger.missingEvidence) {
      lines.push(`- ${ev}`);
    }
    lines.push('');
    lines.push('## How To Produce The Missing Evidence');
    for (const ev of trigger.missingEvidence) {
      const node = findEvidenceNode(ev);
      if (node) {
        lines.push(`### ${ev}`);
        lines.push(firstSentence(node.rule));
        if (node.detectionMethod) {
          lines.push('');
          lines.push(`**How**: ${node.detectionMethod}`);
        }
        if (node.fixTemplate) {
          lines.push('');
          lines.push('```');
          lines.push(node.fixTemplate);
          lines.push('```');
        }
        lines.push('');
      } else {
        lines.push(`### ${ev}`);
        lines.push('Produce mechanical evidence for this requirement.');
        lines.push('');
      }
    }
    return lines.join('\n') + FOOTER;
  }

  // ── PSM Activation ───────────────────────────────────────────
  if (trigger.type === 'psm-activation' && trigger.loopType) {
    lines.push('# Problem Solving Mode Activated');
    lines.push('');
    lines.push(`Detected loop type: **${trigger.loopType}**`);
    lines.push('');
    lines.push(
      'A behavioral loop has been detected. Use the 6-layer scientific ' +
        'method (PSE):',
    );
    lines.push('1. **ASSUMPTION** — state hypothesis + success/disproof criteria');
    lines.push('2. **ACTION** — exact command + expected output');
    lines.push('3. **OBSERVATION** — raw output vs expected');
    lines.push('4. **GAP_ANALYSIS** — identify the root cause');
    lines.push('5. **META_REFLECTION** — double-loop learning');
    lines.push('6. **VERIFICATION** — confirm the fix works mechanically');
    lines.push('');

    const matchState: AgentState = {
      ...state,
      loopType: trigger.loopType,
      phase: 'post-execution',
    };
    const nodes = matchKnowledge(matchState);
    const fixNodes = nodes.filter(
      (n) => n.category === 'fix-pattern' || n.category === 'failure-pattern',
    );
    if (fixNodes.length > 0) {
      lines.push('## Matched Patterns');
      for (const n of fixNodes.slice(0, 3)) {
        lines.push(`### ${n.id}`);
        lines.push(firstSentence(n.rule));
        if (n.fixTemplate) {
          lines.push('```');
          lines.push(n.fixTemplate);
          lines.push('```');
        }
        lines.push('');
      }
    }
    return lines.join('\n') + FOOTER;
  }

  // ── Error Encountered ────────────────────────────────────────
  if (trigger.type === 'error-encountered' && trigger.errorPattern) {
    lines.push('# Error Recovery Guidance');
    lines.push('');
    lines.push(`Error pattern: **${trigger.errorPattern}**`);
    lines.push('');

    const matchState: AgentState = {
      ...state,
      errorPattern: trigger.errorPattern,
      phase: 'post-execution',
    };
    const matched = matchKnowledge(matchState);
    let errorNodes = matched.filter((n) => n.category === 'error-recovery');

    // Fallback: direct graph search if context matcher missed it
    if (errorNodes.length === 0) {
      const pat = trigger.errorPattern.toLowerCase();
      errorNodes = ALL_KNOWLEDGE_NODES.filter(
        (n) =>
          n.category === 'error-recovery' &&
          (n.id.toLowerCase().includes(pat) ||
            n.rule.toLowerCase().includes(pat)),
      ).slice(0, 3);
    }

    if (errorNodes.length > 0) {
      lines.push('## Matched Recovery Patterns');
      for (const n of errorNodes.slice(0, 3)) {
        lines.push(`### ${n.id}`);
        lines.push(firstSentence(n.rule));
        if (n.fixTemplate) {
          lines.push('```');
          lines.push(n.fixTemplate);
          lines.push('```');
        }
        lines.push('');
      }
    } else {
      lines.push(
        'No exact match in the knowledge graph. Analyze the error output ' +
          'directly: identify the file, line, and root cause, then apply the ' +
          'appropriate fix.',
      );
      lines.push('');
    }
    return lines.join('\n') + FOOTER;
  }

  // ── Enforcement Block ────────────────────────────────────────
  if (trigger.type === 'enforcement-block') {
    lines.push('# Enforcement Block Detected');
    lines.push('');
    lines.push(`Gate: **${gateUpper}**`);
    lines.push('');
    lines.push(
      'Enforcement has blocked an action. Review the violation and fix the ' +
        'root cause before retrying — do not attempt to bypass enforcement.',
    );
    lines.push('');

    const nodes = matchKnowledge({ ...state, phase: 'post-execution' });
    const apNodes = nodes.filter(
      (n) => n.category === 'anti-pattern' || n.category === 'enforcement',
    );
    if (apNodes.length > 0) {
      lines.push('## Relevant Rules');
      for (const n of apNodes.slice(0, 3)) {
        lines.push(`- **${n.id}**: ${firstSentence(n.rule)}`);
      }
      lines.push('');
    }
    return lines.join('\n') + FOOTER;
  }

  // ── Drift Detected ───────────────────────────────────────────
  if (trigger.type === 'drift-detected') {
    lines.push('# Trajectory Drift Detected');
    lines.push('');
    lines.push(`Gate: **${gateUpper}**`);
    lines.push(`Drift level: **${state.driftLevel ?? 'unknown'}**`);
    lines.push('');
    lines.push('The agent has drifted from the expected trajectory. Re-align now:');
    lines.push('1. Re-read the task scope');
    lines.push('2. Identify the last correct state');
    lines.push('3. Discard unrelated changes');
    lines.push('4. Resume from the correct state');
    lines.push('');

    const nodes = matchKnowledge({ ...state, phase: 'pre-execution' });
    const scopeNodes = nodes.filter(
      (n) => n.category === 'anti-pattern' || n.category === 'principle',
    );
    if (scopeNodes.length > 0) {
      lines.push('## Re-Alignment Guidance');
      for (const n of scopeNodes.slice(0, 3)) {
        lines.push(`- ${firstSentence(n.rule)}`);
      }
      lines.push('');
    }
    return lines.join('\n') + FOOTER;
  }

  // Fallback: generic re-alignment
  lines.push('# Re-Alignment Required');
  lines.push('');
  lines.push(`Gate: **${gateUpper}**`);
  lines.push('');
  lines.push(
    'A re-alignment event has occurred. Review current state and ensure ' +
      'alignment with gate requirements.',
  );
  return lines.join('\n') + FOOTER;
}

// ── Remembering: Compaction Recovery Warhead ─────────────────────

/**
 * Build a compaction-recovery warhead.
 *
 * Reconstructs the model's knowledge state after a context compaction.
 * Contains: current gate, what knowledge has already been provided,
 * current priorities, and evidence status.
 */
function buildCompactionRecoveryWarhead(state: AgentState): string {
  const disclosure = getProgressiveDisclosure();
  const injected = disclosure.getAllInjected();
  const gateUpper = (state.gate || 'plan').toUpperCase();
  const gateNodes = getGateNodes(state.gate);

  const lines: string[] = [];
  lines.push('# Session Recovery');
  lines.push('');
  lines.push(`## Current Gate: ${gateUpper}`);
  lines.push('');

  // What's been done
  if (injected.length > 0) {
    lines.push('## Knowledge Already Provided');
    lines.push(
      `${injected.length} guidance item${injected.length === 1 ? '' : 's'} ` +
        `injected this session.`,
    );
    lines.push('');
  } else {
    lines.push('## Knowledge Already Provided');
    lines.push('No guidance has been injected yet this session.');
    lines.push('');
  }

  // Current gate guidance — priorities
  const keyNodes = gateNodes
    .filter((n) => n.severity === 'block' || n.severity === 'warn')
    .slice(0, 5);
  if (keyNodes.length > 0) {
    lines.push('## Current Priorities');
    for (const n of keyNodes) {
      lines.push(`- ${substituteWarheadTemplate(n.bulletTemplate, state)}`);
    }
    lines.push('');
  }

  // Evidence status
  lines.push('## Evidence Status');
  if (state.evidenceRegistered.length > 0) {
    lines.push(`Registered: ${state.evidenceRegistered.join(', ')}`);
  } else {
    lines.push('No evidence registered yet.');
  }
  lines.push('');

  lines.push('## Next Steps');
  lines.push(
    'Continue producing evidence for the current gate. Call ' +
      '`shark-gate advance` when all requirements are met.',
  );

  return (
    lines.join('\n') +
    FOOTER.replace('Warhead Generator', 'Warhead Generator — Compaction Recovery')
  );
}

// ── Token Range Enforcement ──────────────────────────────────────

/**
 * Ensure the warhead content falls within the 300-600 token range.
 *
 * - If too short: pad with relevant gate knowledge until >= 300 tokens.
 * - If too long: truncate at a sentence boundary before 600 tokens.
 */
function enforceTokenRange(content: string, state: AgentState): string {
  if (estimateTokens(content) >= MIN_TOKENS && estimateTokens(content) <= MAX_TOKENS) {
    return content;
  }

  let result = content;

  if (estimateTokens(result) < MIN_TOKENS) {
    result = padWarhead(result, state);
  }

  if (estimateTokens(result) > MAX_TOKENS) {
    result = truncateToMaxTokens(result);
  }

  return result;
}

/**
 * Pad a warhead with additional relevant knowledge to reach MIN_TOKENS.
 *
 * Inserts linked iron-laws/principles and full gate-knowledge rules.
 */
function padWarhead(content: string, state: AgentState): string {
  const lines = content.split('\n');

  // Strip the footer — we'll re-add it after padding
  const footerIdx = lines.findIndex((l) => l.startsWith('---'));
  if (footerIdx !== -1) {
    lines.splice(footerIdx);
  }

  const gateNodes = getGateNodes(state.gate);

  // Add linked iron-laws and principles
  const linkedLawIds = new Set(gateNodes.flatMap((n) => n.links));
  const refNodes = ALL_KNOWLEDGE_NODES.filter(
    (n) =>
      (n.category === 'iron-law' || n.category === 'principle') &&
      linkedLawIds.has(n.id),
  ).slice(0, 5);

  if (refNodes.length > 0) {
    lines.push('## Key Engineering Laws');
    for (const n of refNodes) {
      lines.push(`- **${n.id}**: ${firstSentence(n.rule)}`);
    }
    lines.push('');
  }

  let result = lines.join('\n') + FOOTER;

  // If still short, inject full gate-knowledge rules
  if (estimateTokens(result) < MIN_TOKENS) {
    const extra = gateNodes.filter((n) => n.category === 'gate-knowledge').slice(0, 6);
    if (extra.length > 0) {
      const extraLines: string[] = ['', '## Full Gate Requirements'];
      for (const n of extra) {
        extraLines.push(`- **${n.id}**: ${n.rule}`);
      }
      extraLines.push('');
      const insertPoint = result.indexOf('\n---');
      if (insertPoint !== -1) {
        result =
          result.slice(0, insertPoint) +
          '\n' +
          extraLines.join('\n') +
          result.slice(insertPoint);
      }
    }
  }

  return result;
}

/**
 * Truncate a warhead to MAX_TOKENS at a line boundary.
 */
function truncateToMaxTokens(content: string): string {
  const maxChars = MAX_TOKENS * CHARS_PER_TOKEN;
  if (content.length <= maxChars) return content;

  // Cut at the last newline before the limit (preserve complete lines)
  let cut = content.lastIndexOf('\n', maxChars);
  if (cut === -1 || cut < maxChars * 0.5) {
    cut = maxChars;
  }

  return (
    content.slice(0, cut).trimEnd() +
    '\n\n---\n_Generated by EIE Warhead Generator (truncated)_'
  );
}

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Extract the first sentence from a text block.
 */
function firstSentence(text: string): string {
  const match = text.match(/^[^.!?]*[.!?]/);
  if (match) return match[0].trim();
  // No sentence terminator — return first line, trimmed
  return text.split('\n')[0].trim();
}

/**
 * Get nodes for a gate, normalizing case to uppercase (node conditions
 * use uppercase gate names like 'PLAN', 'BUILD', etc.).
 */
function getGateNodes(gate: string): KnowledgeNode[] {
  const upper = (gate || 'PLAN').toUpperCase();
  const found = getNodesForGate(upper);
  if (found.length > 0) return found;
  // Fallback to original case if uppercase matched nothing
  return getNodesForGate(gate);
}

/**
 * Find a knowledge node relevant to a specific evidence ID.
 *
 * Searches by evidenceSpec.id, node ID, and rule content.
 */
function findEvidenceNode(evId: string): KnowledgeNode | undefined {
  const lower = evId.toLowerCase();
  return ALL_KNOWLEDGE_NODES.find(
    (n) =>
      n.evidenceSpec?.id === lower ||
      n.evidenceSpec?.id === evId ||
      n.id.toLowerCase().includes(lower),
  );
}

/**
 * Substitute template variables in a warhead or bullet template.
 *
 * Supported placeholders: {gate}, {tool}, {fn}, {line}, {file}, {evidence}
 */
function substituteWarheadTemplate(template: string, state: AgentState): string {
  return template
    .replace(/\{gate\}/g, state.gate)
    .replace(/\{tool\}/g, state.toolName)
    .replace(/\{fn\}/g, state.currentFunction ?? 'unknown')
    .replace(/\{line\}/g, String(state.currentLine ?? 0))
    .replace(/\{file\}/g, state.filePath?.split('/').pop() ?? 'file')
    .replace(/\{evidence\}/g, state.evidenceRegistered.join(', '));
}
