import type { LayerRule } from '../types.js';
import { OperationType } from '../types.js';

export const L5_17_RETARD_LOGIC: LayerRule = {
  layer: 'L5.17',
  description: 'Retard Logic — blocks self-contradiction, basic nonsense, excuses, and off-topic behavior',
  applicableTo: [OperationType.READ, OperationType.WRITE, OperationType.EXECUTE, OperationType.TEST, OperationType.SYSTEM],
  patterns: [
    {
      intent: OperationType.READ,
      pattern: /\b(but|however|yet|although)\s+(not\s+)?(it|the|this|that)\b.*\1/gi,
      field: 'args.description',
      description: 'Self-contradiction detected',
    },
    {
      intent: OperationType.READ,
      pattern: /\b(but|however|yet|although)\s+(not\s+)?(it|the|this|that)\b.*\1/gi,
      field: 'args.notes',
      description: 'Self-contradiction detected in notes',
    },
    {
      intent: OperationType.WRITE,
      pattern: /\b(always\s+never|never\s+always)\b/i,
      field: 'args.description',
      description: 'Logical impossibility detected',
    },
    {
      intent: OperationType.WRITE,
      pattern: /\b(always\s+never|never\s+always)\b/i,
      field: 'args.notes',
      description: 'Logical impossibility detected in notes',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(can'?t|won'?t|doesn'?t)\s+(really|actually)\s+(help|do|fix|work)\b/i,
      field: 'args.description',
      description: 'Defeatist excuse — STOP complaining and fix it',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(can'?t|won'?t|doesn'?t)\s+(really|actually)\s+(help|do|fix|work)\b/i,
      field: 'args.notes',
      description: 'Defeatist excuse in notes — STOP complaining and fix it',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(not\s+my|not\s+our)\s+(job|problem|fault|responsibility)\b/i,
      field: 'args.description',
      description: 'Responsibility deflection — own the problem',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(not\s+my|not\s+our)\s+(job|problem|fault|responsibility)\b/i,
      field: 'args.notes',
      description: 'Responsibility deflection in notes — own the problem',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(that'?s|this\s+is)\s+(just|not)\s+(how|what)\s+(it\s+)?(works?|happens)\b/i,
      field: 'args.description',
      description: 'Dismissive excuse without evidence',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(that'?s|this\s+is)\s+(just|not)\s+(how|what)\s+(it\s+)?(works?|happens)\b/i,
      field: 'args.notes',
      description: 'Dismissive excuse in notes without evidence',
    },
    {
      intent: OperationType.SYSTEM,
      pattern: /\b(model\s+(quota|limit|restriction)|rate\s+limit|api\s+key|too\s+expensive)\b/i,
      field: 'args.description',
      description: 'Model restriction excuse — quality gates apply regardless',
    },
    {
      intent: OperationType.SYSTEM,
      pattern: /\b(model\s+(quota|limit|restriction)|rate\s+limit|api\s+key|too\s+expensive)\b/i,
      field: 'args.notes',
      description: 'Model restriction excuse in notes — quality gates apply regardless',
    },
    {
      intent: OperationType.READ,
      pattern: /\b(over.?simplif|too\s+simpl|hand.?wave|glossed?\s+over)\b/i,
      field: 'args.description',
      description: 'Oversimplification detected — nuance matters',
    },
    {
      intent: OperationType.READ,
      pattern: /\b(over.?simplif|too\s+simpl|hand.?wave|glossed?\s+over)\b/i,
      field: 'args.notes',
      description: 'Oversimplification detected in notes — nuance matters',
    },
    {
      intent: OperationType.TEST,
      pattern: /\b(sorta|kinda|more\s+or\s+less|mostly|approximately)\s+(works?|correct|functional)\b/i,
      field: 'args.description',
      description: 'Confusion pretense — "sorta works" is not acceptable',
    },
    {
      intent: OperationType.TEST,
      pattern: /\b(sorta|kinda|more\s+or\s+less|mostly|approximately)\s+(works?|correct|functional)\b/i,
      field: 'args.notes',
      description: 'Confusion pretense in notes — "sorta works" is not acceptable',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(not\s+worth\s+(the\s+)?(effort|it)|too\s+much\s+work|diminishing\s+returns)\b/i,
      field: 'args.description',
      description: 'Undermining — quality gates exist for a reason',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(not\s+worth\s+(the\s+)?(effort|it)|too\s+much\s+work|diminishing\s+returns)\b/i,
      field: 'args.notes',
      description: 'Undermining in notes — quality gates exist for a reason',
    },
    {
      intent: OperationType.READ,
      pattern: /\b(off.?topic|irrelevant|unrelated|not\s+(related|relevant))\b.*?$/i,
      field: 'args.description',
      description: 'Off-topic behavior detected — stay on task',
    },
    {
      intent: OperationType.READ,
      pattern: /\b(off.?topic|irrelevant|unrelated|not\s+(related|relevant))\b.*?$/i,
      field: 'args.notes',
      description: 'Off-topic behavior in notes — stay on task',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(evil\.com|example\.com|test\.com|dummy\.com|placeholder)\b/i,
      field: 'command',
      description: 'Non-sensical test target — use real targets or container isolation',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(evil\.com|example\.com|test\.com|dummy\.com|placeholder)\b/i,
      field: 'args.description',
      description: 'Non-sensical test target described — use real targets',
    },
    {
      intent: OperationType.EXECUTE,
      pattern: /\b(evil\.com|example\.com|test\.com|dummy\.com|placeholder)\b/i,
      field: 'args.notes',
      description: 'Non-sensical test target in notes — use real targets',
    },
  ],
  correction: 'Think harder. Stop making excuses. Own the problem. Verify mechanically.',
  enabled: true,
};
