/**
 * src/eie/nodes/analysis-orders.ts — 6 Analysis Order Nodes (AO0-AO5)
 *
 * The 6 Orders of Program Analysis from Runtime Grade Bible §1.
 * Each order represents a progressively deeper analysis capability.
 * Lower orders filter before higher orders run.
 *
 * IL14: Analysis order matters. Always run 0→1→2→3→4→5.
 *
 * Source: RUNTIME_GRADE_BIBLE.md §1 + T3_ALGORITHMIC_SYSTEMS.md
 */

import type { KnowledgeNode } from '../types';

// ══ AO0: PASS-THROUGH ══════════════════════════════════════════

export const AO0_PASS_THROUGH: KnowledgeNode = {
  id: 'AO0-PASS-THROUGH',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 0,
  rule: [
    'ORDER 0 — PASS-THROUGH: No analysis performed. Code passes through unchanged.',
    'This is the baseline. No filtering, no transformation, no verification.',
    'Order 0 is used for trusted, verified code that has already passed all gates.',
    'It is also the default state before any analysis provider is registered.',
    'Order 0 should be used ONLY for code that has been through the full audit pipeline.',
    'Using Order 0 on untrusted code means zero safety — all defects pass through.',
    'Anti-pattern: Setting the entire codebase to Order 0 to "speed up" the build.',
  ].join('\n'),
  detectionMethod: 'Check GATE_ANALYSIS_ROUTING for order 0 assignments. Verify no untrusted code is routed to order 0.',
  fixTemplate: 'Only assign order 0 to code that has passed audit gate R22 (claim-reality verification). All other code must use order 1+.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Order 0 (pass-through) on untrusted code. Raise to Order 1+ for safety.',
  warheadTemplate: [
    '# AO0 — Pass-Through Analysis',
    '',
    '## Definition',
    'No analysis. Code flows through unchecked.',
    '',
    '## When to Use',
    'ONLY for previously-verified code (post-AUDIT). Never for new code.',
    '',
    '## Anti-Pattern',
    'Routing all code to Order 0 to bypass analysis — this disables all safety.',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-config', verify: 'fs-check', minQuality: 0.90 },
  severity: 'guide',
  layer: 0,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'AO1-REGEX-CANDIDATE', 'AO2-AST-WALKER'],
  selfVerified: true,
};

// ══ AO1: REGEX / CANDIDATE GENERATION ══════════════════════════

export const AO1_REGEX_CANDIDATE: KnowledgeNode = {
  id: 'AO1-REGEX-CANDIDATE',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 1,
  rule: [
    'ORDER 1 — REGEX / CANDIDATE GENERATION: Fast pattern matching for obvious violations.',
    'Uses regular expressions to identify candidate violations in source text.',
    'Examples: empty catch blocks (catch\\s*\\{\\s*\\}), hardcoded paths (/home/[^/]+/), any-typed params.',
    'CAN detect: Surface-level patterns, string literals matching known defect signatures.',
    'CANNOT detect: Type relationships, structural context, control flow, data flow, semantic meaning.',
    'Order 1 is the fastest filter — it eliminates obvious violations before expensive AST analysis.',
    'Anti-pattern: Using regex as the ONLY analysis (misses type and structural defects entirely).',
  ].join('\n'),
  detectionMethod: 'Verify order 1 providers are registered as warhead hooks with regex patterns. Check that order 1 runs before orders 2-5.',
  fixTemplate: 'Register regex-based candidate generators for each T1 principle. Pipeline: text → regex match → candidate list → pass to order 2.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Order 1 regex candidate generation missing for {pattern}. Add regex hook.',
  warheadTemplate: [
    '# AO1 — Regex / Candidate Generation',
    '',
    '## Definition',
    'Fast regex-based scanning that identifies candidate violations.',
    '',
    '## Can Detect',
    '- Empty catch blocks (regex: catch\\s*\\{\\s*\\})',
    '- Hardcoded paths (regex: /home/[^/]+/)',
    '- `any` type annotations (regex: :\\s*any\\b)',
    '- Comment-only catches (regex: catch\\s*\\{\\s*/\\*)',
    '',
    '## Cannot Detect',
    '- Type relationships (requires Order 3)',
    '- Structural context (requires Order 2)',
    '- Control flow defects (requires Order 4)',
    '',
    '## Anti-Pattern',
    'Regex-as-only-analysis: Using regex alone misses structural and type-level defects.',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-config', verify: 'fs-check', minQuality: 0.90 },
  severity: 'warn',
  layer: 1,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'AO0-PASS-THROUGH', 'AO2-AST-WALKER', 'AO3-TYPECHECKER'],
  selfVerified: true,
};

// ══ AO2: AST WALKER ════════════════════════════════════════════

export const AO2_AST_WALKER: KnowledgeNode = {
  id: 'AO2-AST-WALKER',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 2,
  rule: [
    'ORDER 2 — AST WALKER: Structural analysis using Abstract Syntax Tree traversal.',
    'Parses source code into an AST and walks the tree to detect structural defects.',
    'Uses forEachChild, type guards (ts.isCallExpression, ts.isFunctionDeclaration), and parent tracking.',
    'CAN detect: Unwired exports, missing guards before casts, structural anti-patterns, dead code paths.',
    'CANNOT detect: Type assignability, type inference results, interface conformance.',
    'Order 2 catches structural defects that regex cannot see — nested patterns, scope context.',
    'Anti-pattern: Re-implementing forEachChild manually instead of using the TypeScript visitor pattern.',
  ].join('\n'),
  detectionMethod: 'Verify order 2 providers parse source to AST (ts.createSourceFile) and walk with visitor pattern. Check that structural rules are checked.',
  fixTemplate: 'import * as ts from "typescript"; const sf = ts.createSourceFile(path, content, ts.ScriptTarget.Latest, true); walk(sf);',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Order 2 AST analysis needed for {rule}. Implement AST visitor for structural check.',
  warheadTemplate: [
    '# AO2 — AST Walker Analysis',
    '',
    '## Definition',
    'Structural analysis via AST traversal using TypeScript compiler API.',
    '',
    '## Can Detect',
    '- Unwired exports (exported functions never imported)',
    '- Missing guards before type assertions',
    '- Structural anti-patterns (nested catches, orphan returns)',
    '- Dead code paths (unreachable statements)',
    '- forEachChild visitor pattern violations',
    '',
    '## Cannot Detect',
    '- Type assignability (requires Order 3)',
    '- Control flow across functions (requires Order 4)',
    '- Runtime behavior (requires Order 5)',
    '',
    '## When to Use',
    'For all structural rules: SemanticFirewall checks, dead export detection, scope validation.',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-config', verify: 'fs-check', minQuality: 0.90 },
  severity: 'warn',
  layer: 2,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'AO1-REGEX-CANDIDATE', 'AO3-TYPECHECKER', 'AO4-CFG-DFA'],
  selfVerified: true,
};

// ══ AO3: TYPECHECKER QUERIES ═══════════════════════════════════

export const AO3_TYPECHECKER: KnowledgeNode = {
  id: 'AO3-TYPECHECKER',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 3,
  rule: [
    'ORDER 3 — TYPECHECKER QUERIES: Full type analysis using TypeScript TypeChecker.',
    'Creates a Program with a CompilerHost, gets the TypeChecker, and queries types at AST nodes.',
    'Key APIs: getTypeAtLocation(node), isTypeAssignableTo(source, target), getSymbolAtLocation(node).',
    'CAN detect: Type mismatches, unsafe casts, missing interface implementations, union type narrowing.',
    'CANNOT detect: Runtime behavior, async timing issues, resource lifecycle, execution path coverage.',
    'Order 3 is the most expensive static analysis — it instantiates the full type system.',
    'Anti-pattern: Creating a new Program for each file instead of sharing one Program across all files.',
  ].join('\n'),
  detectionMethod: 'Verify order 3 providers create a shared Program, get TypeChecker, and query types. Check isTypeAssignableTo usage.',
  fixTemplate: [
    'const program = ts.createProgram(files, opts);',
    'const checker = program.getTypeChecker();',
    'const type = checker.getTypeAtLocation(node);',
    'const assignable = checker.isTypeAssignableTo(sourceType, targetType);',
  ].join('\n'),
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Order 3 TypeChecker analysis needed for {rule}. Use checker.getTypeAtLocation + isTypeAssignableTo.',
  warheadTemplate: [
    '# AO3 — TypeChecker Query Analysis',
    '',
    '## Definition',
    'Full type system analysis using TypeScript TypeChecker API.',
    '',
    '## Can Detect',
    '- Type assignability violations (isTypeAssignableTo returns false)',
    '- Unsafe casts (type assertion where source != target)',
    '- Missing interface methods (getSymbolAtLocation + declarations)',
    '- Union type narrowing errors',
    '- Generic constraint violations',
    '',
    '## Cannot Detect',
    '- Control flow defects (requires Order 4)',
    '- Runtime behavior (requires Order 5)',
    '',
    '## When to Use',
    'For all type-safety rules: P2 Type Certainty, output contract verification, generic constraints.',
    '',
    '## Key APIs',
    '- checker.getTypeAtLocation(node)',
    '- checker.isTypeAssignableTo(source, target)',
    '- checker.getSymbolAtLocation(node)',
    '- checker.getPropertiesOfType(type)',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-config', verify: 'fs-check', minQuality: 0.90 },
  severity: 'warn',
  layer: 3,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'AO2-AST-WALKER', 'AO4-CFG-DFA', 'AO5-EXECUTION-VERIFICATION'],
  selfVerified: true,
};

// ══ AO4: CFG / DFA ═════════════════════════════════════════════

export const AO4_CFG_DFA: KnowledgeNode = {
  id: 'AO4-CFG-DFA',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 4,
  rule: [
    'ORDER 4 — CFG / DFA: Control Flow Graph and Data Flow Analysis.',
    'Builds a control flow graph from the AST and traces data flow through the graph.',
    'CAN detect: Floating promises, resource leaks (missing finally cleanup), unreachable code, dead branches.',
    'CAN detect: Torn state (mutations across await boundaries), unhandled rejection paths, missing error paths.',
    'CANNOT detect: Actual runtime behavior — it is static analysis, not execution.',
    'Order 4 requires a complete CFG builder and a data flow tracer — the most complex static analysis.',
    'Anti-pattern: Tracing only the happy path in CFG analysis — error paths are where defects hide.',
  ].join('\n'),
  detectionMethod: 'Verify order 4 providers build a CFG (ts.ControlFlowGraph) and trace all exit paths including catch and finally.',
  fixTemplate: 'Build CFG: const cfg = analyzer.buildControlFlowGraph(fnNode). For each resource acquisition, verify cleanup exists on ALL exit paths.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Order 4 CFG/DFA analysis needed for {rule}. Trace ALL exit paths including error paths.',
  warheadTemplate: [
    '# AO4 — Control Flow Graph / Data Flow Analysis',
    '',
    '## Definition',
    'Control flow graph construction and data flow tracing for deep defect detection.',
    '',
    '## Can Detect',
    '- Floating promises (no .catch on any exit path)',
    '- Resource leaks (cleanup missing on ANY exit path)',
    '- Unreachable code (dead branches in CFG)',
    '- Torn state (mutations across await without finally)',
    '- Unhandled rejection paths',
    '- Missing error handling on specific branches',
    '',
    '## Cannot Detect',
    '- Actual runtime values (requires Order 5)',
    '- Type-level issues (that is Order 3)',
    '',
    '## When to Use',
    'For: P4 Resource Lifecycle, P5 Atomic State, P9 Async Discipline, IL06 Resource Ownership.',
    '',
    '## Key Pattern',
    '1. Build CFG from function node',
    '2. For each resource acquisition, find ALL exit paths',
    '3. Verify cleanup exists on EVERY exit path (including catch, finally, early returns)',
    '4. If any path lacks cleanup, flag as defect.',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-config', verify: 'fs-check', minQuality: 0.90 },
  severity: 'warn',
  layer: 4,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'AO3-TYPECHECKER', 'AO5-EXECUTION-VERIFICATION', 'AO2-AST-WALKER'],
  selfVerified: true,
};

// ══ AO5: EXECUTION VERIFICATION ════════════════════════════════

export const AO5_EXECUTION_VERIFICATION: KnowledgeNode = {
  id: 'AO5-EXECUTION-VERIFICATION',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'analysis-order',
  analysisOrder: 5,
  rule: [
    'ORDER 5 — EXECUTION VERIFICATION: Runtime verification through actual execution.',
    'Compares filesystem state before and after execution (Merkle tree diff).',
    'Runs tests and verifies exit codes, pass rates, and output content.',
    'Runs RGE and compares violation counts before and after.',
    'CAN detect: Theatrical code (no filesystem change), evidence fabrication, claim-reality gaps.',
    'CANNOT be bypassed: The filesystem is the ground truth. The agent cannot rephrase reality.',
    'Order 5 is the most expensive but the most accurate — it is the ONLY order that catches runtime defects.',
    'Anti-pattern: Claiming work was done without order 5 verification — "I ran the tests" is not evidence.',
  ].join('\n'),
  detectionMethod: 'Verify order 5 providers perform: (1) Merkle snapshot before, (2) execute, (3) Merkle snapshot after, (4) diff comparison.',
  fixTemplate: 'snapshotBefore = merkleTree(rootDir); execute(); snapshotAfter = merkleTree(rootDir); const diff = compareMerkle(snapshotBefore, snapshotAfter);',
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'TEST', 'AUDIT', 'DELIVERY'] },
  ],
  bulletTemplate: 'Order 5 verification required: filesystem must change to prove work was done.',
  warheadTemplate: [
    '# AO5 — Execution Verification',
    '',
    '## Definition',
    'Runtime verification through actual execution and filesystem diff comparison.',
    '',
    '## Can Detect',
    '- Theatrical code (no filesystem change after claimed work)',
    '- Evidence fabrication (claims don\'t match FS reality)',
    '- Claim-reality gaps (agent prose vs actual state)',
    '- Test authenticity (do tests actually run and pass?)',
    '- Build authenticity (does the build actually produce output?)',
    '',
    '## Cannot Be Bypassed',
    'The filesystem is ground truth. The agent cannot rephrase reality.',
    'IL01: "The only truth is what the filesystem contains after execution."',
    '',
    '## When to Use',
    'For ALL gate advances. Required evidence: Merkle diff + test results + RGE scores.',
    '',
    '## Triple Evidence Rule (IL15)',
    '1. FILESYSTEM DIFF — Merkle tree before/after',
    '2. TEST EXECUTION — Run before/after, compare pass rates',
    '3. RGE SCORING — Run before/after, compare violations',
    '',
    '## Reference',
    'IL14-ANALYSIS-ORDER-MATTERS — RGB §1 + IL01-OUTPUT-IS-REALITY',
  ].join('\n'),
  evidenceSpec: { id: 'execution-verified', verify: 'diff-check', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL14-ANALYSIS-ORDER-MATTERS', 'IL01-OUTPUT-IS-REALITY', 'IL10-EVIDENCE-IS-MECHANICAL', 'IL15-EVIDENCE-TRIPLE-RULE', 'AO4-CFG-DFA'],
  selfVerified: true,
};

// EXPORTS
export const analysisOrders: KnowledgeNode[] = [
  AO0_PASS_THROUGH,
  AO1_REGEX_CANDIDATE,
  AO2_AST_WALKER,
  AO3_TYPECHECKER,
  AO4_CFG_DFA,
  AO5_EXECUTION_VERIFICATION,
];
