/**
 * src/eie/nodes/gate-requirements.ts — 36 Gate Requirement Nodes
 *
 * 6 gates (PLAN, BUILD, VERIFY, TEST, AUDIT, DELIVERY) × 6 evidence types.
 * Each gate requires specific, mechanical evidence. Each evidence type
 * maps to a verification method. The EIE injects gate-specific knowledge
 * on gate entry and gate rejection.
 *
 * Gate order (immutable): PLAN → BUILD → VERIFY → TEST → AUDIT → DELIVERY
 *
 * Source: EIE_DESIGN_SPEC.md §8 + RUNTIME_GRADE_BIBLE.md + SPEC.md
 */

import type { KnowledgeNode } from '../types';

// ═══════════════════════════════════════════════════════════════
// GATE: PLAN — Evidence: SPEC.md, GuardianConfig.json, Architecture,
//        Error Strategy, Build Order, Scope Definition
// ═══════════════════════════════════════════════════════════════

export const GR_PLAN_SPEC: KnowledgeNode = {
  id: 'GR-PLAN-SPEC',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — SPEC.md Evidence: A SPEC.md file must exist at the project root.',
    'The spec must contain: Project Overview, Architecture, Components, Test Protocol.',
    'The spec must be written BEFORE coding begins — it defines what to build.',
    'Verification: fs.existsSync("SPEC.md") returns true AND file size > 500 bytes.',
    'The spec is the contract. The code must match it. The audit gate verifies alignment.',
    'Without a spec, the agent is coding blindly — no goal, no success criteria.',
    'The spec must be markdown with clear section headers for spec-read verification.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify SPEC.md exists, is >500 bytes, and contains headers: "Project Overview", "Architecture", "Components".',
  fixTemplate: 'Create SPEC.md with: # Title, ## Project Overview, ## Architecture, ## Components, ## Test Protocol. Each section must have real content.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'spec' },
  ],
  bulletTemplate: 'SPEC.md missing or incomplete. Create it with Project Overview, Architecture, Components sections.',
  warheadTemplate: [
    '# PLAN Gate: SPEC.md Required',
    '',
    '## What This Gate Needs',
    'A SPEC.md file at the project root defining what to build.',
    '',
    '## Required Sections',
    '- Project Overview (name, version, type, entry point)',
    '- Architecture (triple-brain, enforcement lobes, gate chain)',
    '- Components (shared layer, hooks, tools)',
    '- Test Protocol (T2 TUI testing bible)',
    '',
    '## How to Produce',
    'Write SPEC.md BEFORE coding. The spec is the contract.',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-SPEC',
  ].join('\n'),
  evidenceSpec: { id: 'spec', verify: 'spec-read', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['IL19-GATE-ORDER-IMMUTABLE', 'GR-PLAN-GUARDIAN', 'R16-BIBLE-ENFORCEMENT'],
  selfVerified: true,
};

export const GR_PLAN_GUARDIAN: KnowledgeNode = {
  id: 'GR-PLAN-GUARDIAN',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — GuardianConfig Evidence: Guardian protection zones must be configured.',
    'The Guardian protects filesystem zones: SANDBOX, DEVELOPMENT, WORKSPACE, PERSONAL, CONFIG, SYSTEM.',
    'Evidence: GuardianConfig.json or equivalent configuration file must exist.',
    'The Guardian prevents writes outside the workspace — scope violation enforcement.',
    'Without Guardian config, the agent can write anywhere — uncontrolled.',
    'Verification: fs-check for config file + verify zone definitions.',
    'The Guardian is the first line of defense against scope creep and unauthorized writes.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify Guardian configuration exists and defines protection zones.',
  fixTemplate: 'Create GuardianConfig.json with zone definitions: { level: "SANDBOX", paths: [...] }. Initialize Guardian in the plugin entry point.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'guardian-config' },
  ],
  bulletTemplate: 'GuardianConfig missing. Configure zone protection before BUILD gate.',
  warheadTemplate: [
    '# PLAN Gate: Guardian Configuration Required',
    '',
    '## What This Gate Needs',
    'Guardian zone protection configuration to prevent unauthorized filesystem writes.',
    '',
    '## Required',
    'GuardianConfig.json defining protection zones (SANDBOX, DEVELOPMENT, WORKSPACE).',
    '',
    '## How to Produce',
    'Create the config. Initialize Guardian in the entry point. Verify zone enforcement.',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-GUARDIAN',
  ].join('\n'),
  evidenceSpec: { id: 'guardian-config', verify: 'fs-check', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['GR-PLAN-SPEC', 'SF-SCOPE-VIOLATION', 'IL16-DERAILMENT-FIVE-SIGNALS'],
  selfVerified: true,
};

export const GR_PLAN_ARCHITECTURE: KnowledgeNode = {
  id: 'GR-PLAN-ARCHITECTURE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — Architecture Evidence: The architecture must be documented in the spec.',
    'Architecture includes: triple-brain parallel design, enforcement lobes, gate chain.',
    'Each component must be listed with its purpose and file location.',
    'The architecture defines the build order — what to build first.',
    'Failure-mode-first: build error handling and verification before features.',
    'The architecture is the blueprint. Coding without it produces unstructured systems.',
    'The AUDIT gate verifies code-to-architecture alignment.',
  ].join('\n'),
  detectionMethod: 'spec-read: verify SPEC.md contains "## Architecture" section with component descriptions.',
  fixTemplate: 'Add ## Architecture section to SPEC.md with: triple-brain design, enforcement lobes, gate chain, component table.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'architecture' },
  ],
  bulletTemplate: 'Architecture section missing from SPEC.md. Document triple-brain + components + gate chain.',
  warheadTemplate: [
    '# PLAN Gate: Architecture Documentation Required',
    '',
    '## What This Gate Needs',
    'An architecture section in SPEC.md describing the system design.',
    '',
    '## Required Content',
    '- Triple-brain parallel architecture (Execution, Reasoning, System)',
    '- Enforcement lobes (Frontal, Left, Right Hemisphere)',
    '- Gate chain (PLAN → BUILD → VERIFY → TEST → AUDIT → DELIVERY)',
    '- Component table (file → purpose)',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-ARCHITECTURE',
  ].join('\n'),
  evidenceSpec: { id: 'architecture', verify: 'spec-read', minQuality: 0.75 },
  severity: 'warn',
  layer: 5,
  links: ['GR-PLAN-SPEC', 'R16-BIBLE-ENFORCEMENT', 'BO-FAILURE-MODE-FIRST'],
  selfVerified: true,
};

export const GR_PLAN_ERROR_STRATEGY: KnowledgeNode = {
  id: 'GR-PLAN-ERROR-STRATEGY',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — Error Strategy Evidence: The spec must define error handling strategy.',
    'How will errors be caught, logged, and propagated?',
    'What fallback values are acceptable for each component?',
    'The error strategy prevents P3 violations by defining the pattern upfront.',
    'Without an error strategy, developers improvise — producing inconsistent error handling.',
    'The error strategy must specify: logging format, error codes, fallback types.',
    'This is a PLAN gate requirement because error handling is architectural.',
  ].join('\n'),
  detectionMethod: 'spec-read: verify SPEC.md contains error handling strategy section.',
  fixTemplate: 'Add ## Error Handling section to SPEC.md: catch pattern, logging format, fallback values, propagation rules.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'error-strategy' },
  ],
  bulletTemplate: 'Error strategy missing from SPEC.md. Define: catch pattern, logging, fallbacks.',
  warheadTemplate: [
    '# PLAN Gate: Error Strategy Required',
    '',
    '## What This Gate Needs',
    'A documented error handling strategy in the spec.',
    '',
    '## Required',
    '- Catch pattern (try/catch/finally in all async paths)',
    '- Logging format (structured JSON with context)',
    '- Fallback values for each component',
    '- Propagation rules (when to throw vs return error)',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-ERROR-STRATEGY',
  ].join('\n'),
  evidenceSpec: { id: 'error-strategy', verify: 'spec-read', minQuality: 0.75 },
  severity: 'warn',
  layer: 5,
  links: ['P3-ERROR-COMPLETENESS', 'IL04-NO-SILENT-FAILURE', 'GR-PLAN-ARCHITECTURE'],
  selfVerified: true,
};

export const GR_PLAN_BUILD_ORDER: KnowledgeNode = {
  id: 'GR-PLAN-BUILD-ORDER',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — Build Order Evidence: The spec must define the build sequence.',
    'Failure-mode-first: build error handling, resource cleanup, and verification BEFORE features.',
    'The build order prevents architectural debt by establishing foundations first.',
    'Each component must be listed in dependency order — what depends on what.',
    'Shared layer first, then hooks, then tools, then gate engine.',
    'The build order is a PLAN gate requirement because reordering later is expensive.',
    'The AUDIT gate verifies the actual build matches the planned order.',
  ].join('\n'),
  detectionMethod: 'spec-read: verify SPEC.md contains build order / component sequence.',
  fixTemplate: 'Add ## Build Order section to SPEC.md listing components in dependency order.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'build-order' },
  ],
  bulletTemplate: 'Build order missing from SPEC.md. List components in failure-mode-first sequence.',
  warheadTemplate: [
    '# PLAN Gate: Build Order Required',
    '',
    '## What This Gate Needs',
    'A documented build sequence in the spec.',
    '',
    '## Required',
    'Failure-mode-first order: error handling → resource cleanup → verification → features.',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-BUILD-ORDER',
  ].join('\n'),
  evidenceSpec: { id: 'build-order', verify: 'spec-read', minQuality: 0.75 },
  severity: 'warn',
  layer: 5,
  links: ['BO-FAILURE-MODE-FIRST', 'GR-PLAN-ARCHITECTURE', 'R21-BUILD-ORDER'],
  selfVerified: true,
};

export const GR_PLAN_SCOPE: KnowledgeNode = {
  id: 'GR-PLAN-SCOPE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'PLAN GATE — Scope Definition Evidence: The task scope must be clearly defined.',
    'What files are IN scope? What files are OUT of scope?',
    'The scope definition prevents derailment (IL16 signal 1: modifying out-of-scope files).',
    'The Guardian enforces scope by blocking writes outside the defined zone.',
    'Without scope definition, the agent may modify anything — uncontrolled.',
    'Scope must be explicit: list allowed directories and files.',
    'The AUDIT gate verifies no out-of-scope files were modified.',
  ].join('\n'),
  detectionMethod: 'spec-read: verify SPEC.md or task description defines file scope.',
  fixTemplate: 'Define scope in SPEC.md: "In scope: src/. Out of scope: node_modules/, dist/, tests/."',
  conditions: [
    { field: 'gate', op: 'equals', value: 'PLAN' },
    { field: 'evidenceId', op: 'equals', value: 'scope' },
  ],
  bulletTemplate: 'Scope not defined. List in-scope and out-of-scope files in SPEC.md.',
  warheadTemplate: [
    '# PLAN Gate: Scope Definition Required',
    '',
    '## What This Gate Needs',
    'Explicit file scope to prevent derailment.',
    '',
    '## Required',
    'In-scope files and out-of-scope files must be listed.',
    '',
    '## Reference',
    'PLAN Gate — GR-PLAN-SCOPE',
  ].join('\n'),
  evidenceSpec: { id: 'scope', verify: 'spec-read', minQuality: 0.75 },
  severity: 'warn',
  layer: 5,
  links: ['IL16-DERAILMENT-FIVE-SIGNALS', 'SF-SCOPE-VIOLATION', 'GR-PLAN-GUARDIAN'],
  selfVerified: true,
};

// ═══════════════════════════════════════════════════════════════
// GATE: BUILD — Evidence: FileManifest, GitDiff, Type Safety,
//        Error Handling, Resource Cleanup, Anti-Theatrical
// ═══════════════════════════════════════════════════════════════

export const GR_BUILD_FILE_MANIFEST: KnowledgeNode = {
  id: 'GR-BUILD-FILE-MANIFEST',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — File Manifest Evidence: All source files must be listed.',
    'Evidence: FileManifest.json or equivalent listing all created/modified files.',
    'The manifest verifies that the planned files were actually created.',
    'Each file must have a purpose matching the architecture spec.',
    'No orphan files — every file must be part of the architecture.',
    'The manifest is compared against the spec during AUDIT gate.',
    'Files not in the manifest but in the filesystem indicate scope creep.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify FileManifest.json exists and lists all source files with purposes.',
  fixTemplate: 'Create FileManifest.json: [{ path: "src/index.ts", purpose: "entry point" }, ...].',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'file-manifest' },
  ],
  bulletTemplate: 'FileManifest.json missing. List all source files with purposes.',
  warheadTemplate: [
    '# BUILD Gate: File Manifest Required',
    '',
    '## What This Gate Needs',
    'A manifest of all created/modified source files.',
    '',
    '## Required',
    'FileManifest.json with path and purpose for each file.',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-FILE-MANIFEST',
  ].join('\n'),
  evidenceSpec: { id: 'file-manifest', verify: 'fs-check', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'GR-PLAN-ARCHITECTURE'],
  selfVerified: true,
};

export const GR_BUILD_GIT_DIFF: KnowledgeNode = {
  id: 'GR-BUILD-GIT-DIFF',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — Git Diff Evidence: The actual changes must be recorded.',
    'Evidence: GitDiff.txt or git diff output showing all changes.',
    'The diff proves that files were actually modified — not just claimed.',
    'The diff is compared against the file manifest for consistency.',
    'Changes outside scope are flagged as derailment (IL16 signal 1).',
    'The diff must show meaningful content changes, not just whitespace.',
    'This is the filesystem component of the evidence triple rule (IL15).',
  ].join('\n'),
  detectionMethod: 'fs-check: verify GitDiff.txt exists with actual diff content.',
  fixTemplate: 'Run git diff > GitDiff.txt. Verify the diff shows meaningful changes matching the manifest.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'git-diff' },
  ],
  bulletTemplate: 'GitDiff.txt missing. Run git diff and save output.',
  warheadTemplate: [
    '# BUILD Gate: Git Diff Required',
    '',
    '## What This Gate Needs',
    'Recorded diff of all changes made during the build.',
    '',
    '## How to Produce',
    'git diff > GitDiff.txt (or git diff HEAD if new files).',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-GIT-DIFF',
  ].join('\n'),
  evidenceSpec: { id: 'git-diff', verify: 'fs-check', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'IL15-EVIDENCE-TRIPLE-RULE', 'GR-BUILD-FILE-MANIFEST'],
  selfVerified: true,
};

export const GR_BUILD_TYPE_SAFETY: KnowledgeNode = {
  id: 'GR-BUILD-TYPE-SAFETY',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — Type Safety Evidence: No `any` types, no unguarded `as` casts.',
    'All P2 (Type Certainty) violations must be resolved.',
    'Function parameters typed as `any` must be replaced with `unknown`.',
    'Type assertions must be guarded by runtime checks.',
    'Evidence: RGE audit shows 0 critical type-safety findings.',
    'Type safety is a BUILD gate requirement because type errors compound.',
    'The VERIFY gate runs tsc to mechanically verify type safety.',
  ].join('\n'),
  detectionMethod: 'rge-audit: run RGE, verify 0 critical P2/type-safety findings.',
  fixTemplate: 'Replace `any` with `unknown`. Guard every `as` with typeof/instanceof. Run RGE to verify.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'type-safety' },
  ],
  bulletTemplate: 'Type safety violations: {count} P2 findings. Fix `any` types and unguarded `as` casts.',
  warheadTemplate: [
    '# BUILD Gate: Type Safety Required',
    '',
    '## What This Gate Needs',
    'Zero critical type-safety findings from RGE.',
    '',
    '## How to Fix',
    '1. Replace `any` parameters with `unknown`.',
    '2. Guard every `as` cast with a runtime check.',
    '3. Run RGE to verify 0 critical findings.',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-TYPE-SAFETY — P2',
  ].join('\n'),
  evidenceSpec: { id: 'type-safety', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P2-TYPE-CERTAINTY', 'GR-VERIFY-TSC'],
  selfVerified: true,
};

export const GR_BUILD_ERROR_HANDLING: KnowledgeNode = {
  id: 'GR-BUILD-ERROR-HANDLING',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — Error Handling Evidence: No empty/swallowing catch blocks.',
    'All P3 (Error Completeness) violations must be resolved.',
    'Every catch must log, recover, or propagate — never swallow.',
    'Evidence: RGE/SRE audit shows 0 P3/S5 findings.',
    'Error handling is foundational — errors propagate silently without it.',
    'The BUILD gate is where error handling is verified because it is architectural.',
    'Error handling defects found later cost 10x more to fix.',
  ].join('\n'),
  detectionMethod: 'sre-audit + rge-audit: verify 0 P3/S5 (empty catch, swallowing) findings.',
  fixTemplate: 'Every catch must: log with context + recover (return fallback) OR re-throw with context.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'error-handling' },
  ],
  bulletTemplate: 'Error handling violations: {count} P3/S5 findings. Fix empty and swallowing catches.',
  warheadTemplate: [
    '# BUILD Gate: Error Handling Required',
    '',
    '## What This Gate Needs',
    'Zero P3/S5 findings — no empty or swallowing catch blocks.',
    '',
    '## How to Fix',
    'Every catch must log + recover or log + re-throw. See P3 fix template.',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-ERROR-HANDLING — P3/S5',
  ].join('\n'),
  evidenceSpec: { id: 'error-handling', verify: 'sre-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P3-ERROR-COMPLETENESS', 'IL04-NO-SILENT-FAILURE'],
  selfVerified: true,
};

export const GR_BUILD_RESOURCE_CLEANUP: KnowledgeNode = {
  id: 'GR-BUILD-RESOURCE-CLEANUP',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — Resource Cleanup Evidence: All resources cleaned up in finally blocks.',
    'All P4 (Resource Lifecycle) violations must be resolved.',
    'setInterval/setTimeout, file handles, event listeners must be in try/finally.',
    'Evidence: RGE audit shows 0 P4 findings.',
    'Resource leaks in long-running processes cause cascading failures.',
    'The BUILD gate verifies resource cleanup because it is a structural property.',
    'Resource leaks are deterministic — they will fail in production.',
  ].join('\n'),
  detectionMethod: 'rge-audit: verify 0 P4 (resource lifecycle) findings.',
  fixTemplate: 'Wrap all resource usage in try/finally. clearInterval/clearTimeout/close in finally block.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'resource-cleanup' },
  ],
  bulletTemplate: 'Resource cleanup violations: {count} P4 findings. Add try/finally around acquisitions.',
  warheadTemplate: [
    '# BUILD Gate: Resource Cleanup Required',
    '',
    '## What This Gate Needs',
    'Zero P4 findings — all resources cleaned up in finally blocks.',
    '',
    '## How to Fix',
    'Wrap every setInterval/setTimeout/file handle in try/finally with cleanup.',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-RESOURCE-CLEANUP — P4',
  ].join('\n'),
  evidenceSpec: { id: 'resource-cleanup', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P4-RESOURCE-LIFECYCLE', 'IL06-RESOURCE-OWNERSHIP'],
  selfVerified: true,
};

export const GR_BUILD_ANTI_THEATRICAL: KnowledgeNode = {
  id: 'GR-BUILD-ANTI-THEATRICAL',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'BUILD GATE — Anti-Theatrical Evidence: No theatrical code patterns.',
    'All P11 (Output Is The Work) violations must be resolved.',
    'No functions returning completion flags without side effects.',
    'No functions returning file paths without writing the files.',
    'Evidence: SRE audit shows 0 S1 (theatrical return) findings.',
    'Theatrical code is the #1 form of agent deception.',
    'Zero tolerance — every theatrical code instance is a CRITICAL violation.',
  ].join('\n'),
  detectionMethod: 'sre-audit: verify 0 S1 (theatrical return) findings.',
  fixTemplate: 'Remove theatrical code. Perform real work or return action_required with instructions.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'BUILD' },
    { field: 'evidenceId', op: 'equals', value: 'anti-theatrical' },
  ],
  bulletTemplate: 'Theatrical code: {count} S1 findings. Functions must DO work, not claim it.',
  warheadTemplate: [
    '# BUILD Gate: Anti-Theatrical Required',
    '',
    '## What This Gate Needs',
    'Zero S1 findings — no theatrical code.',
    '',
    '## How to Fix',
    'Every function returning a completion flag must have actual side effects.',
    'Every function returning a path must have written the file.',
    '',
    '## Reference',
    'BUILD Gate — GR-BUILD-ANTI-THEATRICAL — P11/S1',
  ].join('\n'),
  evidenceSpec: { id: 'anti-theatrical', verify: 'sre-audit', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['P11-OUTPUT-IS-THE-WORK', 'IL18-THEATRICAL-CODE-ZERO'],
  selfVerified: true,
};

// ═══════════════════════════════════════════════════════════════
// GATE: VERIFY — Evidence: TSC Compilation, Build Output, RGE Score,
//        SRE Score, Type Contract, Import Validity
// ═══════════════════════════════════════════════════════════════

export const GR_VERIFY_TSC: KnowledgeNode = {
  id: 'GR-VERIFY-TSC',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — TypeScript Compilation Evidence: tsc --noEmit must exit 0.',
    'Evidence: tsc exit code 0 with no errors.',
    'This mechanically proves type safety — no `any` leaking, no type mismatches.',
    'The agent cannot self-certify type safety — tsc must run.',
    'tsc is the ground truth for type checking. Agent claims are irrelevant.',
    'If tsc fails, the code is not type-safe. Fix the errors before proceeding.',
    'This is evidence method exec-tsc (EIE §7 method 1).',
  ].join('\n'),
  detectionMethod: 'exec-tsc: run tsc --noEmit (or tsc --project tsconfig.check.json --noEmit), check exit code.',
  fixTemplate: 'Run: tsc --project tsconfig.check.json --noEmit. Fix every error. Re-run until exit 0.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'tsc-compilation' },
  ],
  bulletTemplate: 'tsc compilation failed: {count} errors. Fix type errors, re-run tsc.',
  warheadTemplate: [
    '# VERIFY Gate: TSC Compilation Required',
    '',
    '## What This Gate Needs',
    'tsc --noEmit exits with code 0.',
    '',
    '## How to Produce',
    'Run: tsc --project tsconfig.check.json --noEmit',
    'Fix every error. Re-run until exit 0.',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-TSC — exec-tsc',
  ].join('\n'),
  evidenceSpec: { id: 'tsc-compilation', verify: 'exec-tsc', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['P2-TYPE-CERTAINTY', 'GR-BUILD-TYPE-SAFETY', 'IL10-EVIDENCE-IS-MECHANICAL'],
  selfVerified: true,
};

export const GR_VERIFY_BUILD: KnowledgeNode = {
  id: 'GR-VERIFY-BUILD',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — Build Output Evidence: bun build must produce a bundle.',
    'Evidence: bun build exit code 0 with dist/index.js (or equivalent) produced.',
    'The bundle must be >0 bytes — an empty bundle means the build failed silently.',
    'This mechanically proves the code compiles and bundles.',
    'The agent cannot self-certify builds — bun build must run.',
    'If the build fails, the code is not deployable. Fix errors before proceeding.',
    'This is evidence method exec-build (EIE §7 method 2).',
  ].join('\n'),
  detectionMethod: 'exec-build: run bun build, check exit code. Verify dist/index.js exists and is >0 bytes.',
  fixTemplate: 'Run: bun build src/index.ts --outdir dist --target bun --format esm --bundle. Fix errors. Verify output.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'build-output' },
  ],
  bulletTemplate: 'Build failed: {error}. Fix build errors, re-run bun build.',
  warheadTemplate: [
    '# VERIFY Gate: Build Output Required',
    '',
    '## What This Gate Needs',
    'bun build exits 0 and produces dist/index.js.',
    '',
    '## How to Produce',
    'bun build src/index.ts --outdir dist --target bun --format esm --bundle',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-BUILD — exec-build',
  ].join('\n'),
  evidenceSpec: { id: 'build-output', verify: 'exec-build', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL09-WIRE-DONT-DECLARE', 'R0-BUILD-CHAIN', 'GR-VERIFY-TSC'],
  selfVerified: true,
};

export const GR_VERIFY_RGE_SCORE: KnowledgeNode = {
  id: 'GR-VERIFY-RGE-SCORE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — RGE Score Evidence: Runtime Grade Engine must show 0 critical findings.',
    'Evidence: RGE audit report with critical findings = 0.',
    'RGE checks P1-P12, type safety, contracts, resource lifecycle, etc.',
    'Critical findings in RGE mean the code is not runtime-grade.',
    'The RGE score is mechanical — not the agent\'s assessment.',
    'If RGE finds critical violations, fix them before proceeding to TEST.',
    'This is evidence method rge-audit (EIE §7 method 3).',
  ].join('\n'),
  detectionMethod: 'rge-audit: run RGE, verify critical findings = 0.',
  fixTemplate: 'Run RGE audit. Fix every critical finding. Re-run until 0 critical.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'rge-score' },
  ],
  bulletTemplate: 'RGE has {count} critical findings. Fix all before TEST gate.',
  warheadTemplate: [
    '# VERIFY Gate: RGE Score Required',
    '',
    '## What This Gate Needs',
    'RGE audit with 0 critical findings.',
    '',
    '## How to Fix',
    'Run RGE. Fix every critical finding. Re-run until clean.',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-RGE-SCORE — rge-audit',
  ].join('\n'),
  evidenceSpec: { id: 'rge-score', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P1-DEFENSIVE-IMPORT', 'GR-BUILD-TYPE-SAFETY', 'IL10-EVIDENCE-IS-MECHANICAL'],
  selfVerified: true,
};

export const GR_VERIFY_SRE_SCORE: KnowledgeNode = {
  id: 'GR-VERIFY-SRE-SCORE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — SRE Score Evidence: Slop Removal Engine must show 0 theatrical findings.',
    'Evidence: SRE audit report with S1-S5 findings = 0.',
    'SRE checks for theatrical returns, fake tests, mocks in production, swallowing catches.',
    'S1-S5 findings in SRE mean the code contains theatrical patterns.',
    'The SRE score is mechanical — not the agent\'s assessment.',
    'If SRE finds theatrical patterns, fix them before proceeding to TEST.',
    'This is evidence method sre-audit (EIE §7 method 4).',
  ].join('\n'),
  detectionMethod: 'sre-audit: run SRE, verify S1-S5 findings = 0.',
  fixTemplate: 'Run SRE audit. Fix every S1-S5 finding. Re-run until clean.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'sre-score' },
  ],
  bulletTemplate: 'SRE has {count} theatrical findings (S1-S5). Fix all before TEST gate.',
  warheadTemplate: [
    '# VERIFY Gate: SRE Score Required',
    '',
    '## What This Gate Needs',
    'SRE audit with 0 S1-S5 findings.',
    '',
    '## How to Fix',
    'Run SRE. Fix every theatrical pattern. Re-run until clean.',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-SRE-SCORE — sre-audit',
  ].join('\n'),
  evidenceSpec: { id: 'sre-score', verify: 'sre-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P11-OUTPUT-IS-THE-WORK', 'IL18-THEATRICAL-CODE-ZERO'],
  selfVerified: true,
};

export const GR_VERIFY_TYPE_CONTRACT: KnowledgeNode = {
  id: 'GR-VERIFY-TYPE-CONTRACT',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — Type Contract Evidence: All return types honored across paths.',
    'No catch block returns null/undefined for non-nullable types.',
    'No function implicitly returns undefined when type requires a value.',
    'Evidence: tsc --strict passes + RGE P10 findings = 0.',
    'Type contracts are the boundary between safe and unsafe code.',
    'Breaking a type contract causes runtime TypeErrors in production.',
    'The VERIFY gate mechanically verifies contracts via tsc and RGE.',
  ].join('\n'),
  detectionMethod: 'exec-tsc + rge-audit: tsc --strict passes AND RGE shows 0 P10 findings.',
  fixTemplate: 'Every catch must throw or return a valid value of the declared type. Run tsc --strict.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'type-contract' },
  ],
  bulletTemplate: 'Type contract violations: {count} P10 findings. Fix catch-block return types.',
  warheadTemplate: [
    '# VERIFY Gate: Type Contract Required',
    '',
    '## What This Gate Needs',
    'All return types honored — 0 P10 findings.',
    '',
    '## How to Fix',
    'Fix catch blocks that return null for non-nullable types. Use tsc --strict.',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-TYPE-CONTRACT — P10',
  ].join('\n'),
  evidenceSpec: { id: 'type-contract', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P10-OUTPUT-CONTRACT', 'IL02-CONTRACT-HONORED', 'GR-VERIFY-TSC'],
  selfVerified: true,
};

export const GR_VERIFY_IMPORT_VALIDITY: KnowledgeNode = {
  id: 'GR-VERIFY-IMPORT-VALIDITY',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'VERIFY GATE — Import Validity Evidence: All imports resolve to real exports.',
    'No importing a function that doesn\'t exist on the target module.',
    'No dead imports — imported but never used.',
    'No dead exports — exported but never imported.',
    'Evidence: tsc resolves all imports + RGE P1/P6 findings = 0.',
    'Import failures crash the entire module at load time.',
    'The VERIFY gate mechanically verifies imports via tsc.',
  ].join('\n'),
  detectionMethod: 'exec-tsc + rge-audit: tsc resolves imports AND RGE shows 0 P1/P6 findings.',
  fixTemplate: 'Use namespace imports with typeof guards. Remove dead imports/exports. Run tsc.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'VERIFY' },
    { field: 'evidenceId', op: 'equals', value: 'import-validity' },
  ],
  bulletTemplate: 'Import validity violations: {count} P1/P6 findings. Fix imports and remove dead code.',
  warheadTemplate: [
    '# VERIFY Gate: Import Validity Required',
    '',
    '## What This Gate Needs',
    'All imports resolve — 0 P1/P6 findings.',
    '',
    '## How to Fix',
    'Use namespace imports + typeof guards. Remove dead imports/exports.',
    '',
    '## Reference',
    'VERIFY Gate — GR-VERIFY-IMPORT-VALIDITY — P1/P6',
  ].join('\n'),
  evidenceSpec: { id: 'import-validity', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['P1-DEFENSIVE-IMPORT', 'P6-DEPENDENCY-CHECK', 'IL09-WIRE-DONT-DECLARE'],
  selfVerified: true,
};

// ═══════════════════════════════════════════════════════════════
// GATE: TEST — Evidence: ContainerSpawn, ContainerTest, TUI Interaction,
//        FullSpectrum, Unit Test, Browser Test
// ═══════════════════════════════════════════════════════════════

export const GR_TEST_CONTAINER_SPAWN: KnowledgeNode = {
  id: 'GR-TEST-CONTAINER-SPAWN',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_CONTAINER_TESTING_BIBLE.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — Container Spawn Evidence: Docker container must be spawned and verified.',
    'Deploy dist to runtime-grade-container-sandbox:master.',
    'Verify sha256 checksums match between host and container.',
    'Write opencode.json with the plugin as sole plugin.',
    'Evidence: ContainerSpawnResult.json with spawn details.',
    'The container must be running and responsive before tests proceed.',
    'This is the foundation of all container testing — no container = no tests.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify ContainerSpawnResult.json exists with valid container ID and checksums.',
  fixTemplate: 'Spawn container: docker run with mounted plugin. Verify checksums. Save ContainerSpawnResult.json.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'container-spawn' },
  ],
  bulletTemplate: 'Container spawn failed or missing evidence. Deploy dist, verify checksums.',
  warheadTemplate: [
    '# TEST Gate: Container Spawn Required',
    '',
    '## What This Gate Needs',
    'A running Docker container with the deployed plugin.',
    '',
    '## Required Steps',
    '1. Deploy dist to container.',
    '2. Verify sha256 checksums.',
    '3. Write opencode.json.',
    '4. Save ContainerSpawnResult.json.',
    '',
    '## FORBIDDEN',
    '- opencode run (hooks don\'t fire)',
    '- Direct scripts (node -e, require())',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-CONTAINER-SPAWN — container-tui-test',
  ].join('\n'),
  evidenceSpec: { id: 'container-spawn', verify: 'container-tui-test', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['GR-VERIFY-BUILD', 'IL10-EVIDENCE-IS-MECHANICAL', 'CT-01-CROSS-SOURCE'],
  selfVerified: true,
};

export const GR_TEST_CONTAINER_TEST: KnowledgeNode = {
  id: 'GR-TEST-CONTAINER-TEST',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_CONTAINER_TESTING_BIBLE.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — Container Test Evidence: Full runtime container testing must pass >= 96%.',
    'Wire tmux pipe-pane for stream capture.',
    'Send NATURAL LANGUAGE task via tmux send-keys (two-step Enter).',
    'Monitor pipe-pane with position-tracked poll loop.',
    'Observe MECHANICAL behavior (not text matching).',
    'Evidence: ContainerTestResult.json with pass rate >= 96%.',
    'FORBIDDEN: opencode run, direct scripts, static grep, text matching.',
  ].join('\n'),
  detectionMethod: 'container-tui-test: run full container test suite, verify pass rate >= 96%.',
  fixTemplate: 'Follow the 12-step TUI testing bible. Use tmux send-keys + pipe-pane. Save ContainerTestResult.json.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'container-test' },
  ],
  bulletTemplate: 'Container test pass rate {rate}% (need >= 96%). Fix failing test categories.',
  warheadTemplate: [
    '# TEST Gate: Container Test Required',
    '',
    '## What This Gate Needs',
    'ContainerTestResult.json with pass rate >= 96%.',
    '',
    '## Required Process',
    '1. Wire tmux pipe-pane.',
    '2. Send natural language task via tmux send-keys.',
    '3. Monitor pipe-pane.',
    '4. Observe MECHANICAL behavior.',
    '5. Save ContainerTestResult.json.',
    '',
    '## FORBIDDEN',
    '- opencode run (hooks don\'t fire in run mode)',
    '- Direct scripts (node -e, require())',
    '- Static grep on bundles',
    '- Text matching ("who are you")',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-CONTAINER-TEST — container-tui-test',
  ].join('\n'),
  evidenceSpec: { id: 'container-test', verify: 'container-tui-test', minQuality: 0.96 },
  severity: 'block',
  layer: 5,
  links: ['GR-TEST-CONTAINER-SPAWN', 'IL18-THEATRICAL-CODE-ZERO', 'CT-01-CROSS-SOURCE'],
  selfVerified: true,
};

export const GR_TEST_TUI_INTERACTION: KnowledgeNode = {
  id: 'GR-TEST-TUI-INTERACTION',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_CONTAINER_TESTING_BIBLE.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — TUI Interaction Evidence: Natural language interactions must be observed.',
    'Evidence: TuiInteraction.json with captured input/output.',
    'The agent must respond correctly to natural language tasks in the TUI.',
    'Identity verification: "I am SHARK v{version}" response.',
    'Tool wiring: correct tools available, no foreign tools.',
    'Gate system: chain renders correctly.',
    'Interactions must be MECHANICAL — observed behavior, not text matching.',
  ].join('\n'),
  detectionMethod: 'container-tui-test: capture TUI interactions, verify correct responses.',
  fixTemplate: 'Send natural language tasks via tmux. Capture responses. Save TuiInteraction.json.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'tui-interaction' },
  ],
  bulletTemplate: 'TUI interaction evidence missing. Capture input/output via tmux.',
  warheadTemplate: [
    '# TEST Gate: TUI Interaction Required',
    '',
    '## What This Gate Needs',
    'TuiInteraction.json with captured natural language interactions.',
    '',
    '## Required',
    '- Identity: "I am SHARK v{version}"',
    '- Tool wiring: correct tools, 0 foreign',
    '- Gate chain renders correctly',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-TUI-INTERACTION',
  ].join('\n'),
  evidenceSpec: { id: 'tui-interaction', verify: 'container-tui-test', minQuality: 0.90 },
  severity: 'block',
  layer: 5,
  links: ['GR-TEST-CONTAINER-TEST', 'TUI-01-PLUGIN-LOAD'],
  selfVerified: true,
};

export const GR_TEST_FULL_SPECTRUM: KnowledgeNode = {
  id: 'GR-TEST-FULL-SPECTRUM',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_CONTAINER_TESTING_BIBLE.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — Full Spectrum Evidence: All test categories must pass.',
    'Evidence: FullSpectrumTestResult.json with overall pass rate >= 96%.',
    'Categories: plugin load, identity activation, tool wiring, gate system.',
    'Categories: enforcement brain, destructive command blocking, test runner.',
    'Categories: diagnostics, compaction docs.',
    'Each category must be tested mechanically in the container.',
    'The full spectrum is the comprehensive mechanical evidence.',
  ].join('\n'),
  detectionMethod: 'container-tui-test: run all test categories, aggregate pass rate >= 96%.',
  fixTemplate: 'Run all 9+ test categories. Aggregate results. Save FullSpectrumTestResult.json.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'full-spectrum' },
  ],
  bulletTemplate: 'Full spectrum pass rate {rate}% (need >= 96%). Fix failing categories.',
  warheadTemplate: [
    '# TEST Gate: Full Spectrum Required',
    '',
    '## What This Gate Needs',
    'FullSpectrumTestResult.json with pass rate >= 96%.',
    '',
    '## Test Categories',
    '1. Plugin load & init',
    '2. Identity activation',
    '3. Tool wiring (17+ tools, 0 foreign)',
    '4. Gate system',
    '5. Enforcement brain',
    '6. Destructive command blocking',
    '7. Test runner',
    '8. Diagnostics',
    '9. Compaction docs',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-FULL-SPECTRUM',
  ].join('\n'),
  evidenceSpec: { id: 'full-spectrum', verify: 'container-tui-test', minQuality: 0.96 },
  severity: 'block',
  layer: 5,
  links: ['GR-TEST-CONTAINER-TEST', 'GR-TEST-TUI-INTERACTION'],
  selfVerified: true,
};

export const GR_TEST_UNIT_TEST: KnowledgeNode = {
  id: 'GR-TEST-UNIT-TEST',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — Unit Test Evidence: Unit test suite must pass >= 80%.',
    'Evidence: test runner exit code 0 with pass rate >= 80%.',
    'Unit tests verify individual functions and modules in isolation.',
    'Tests must use real assertions, not hardcoded literals (SRE S2).',
    'No mocks/stubs in unit tests for production code paths (SRE S3).',
    'Unit tests complement container tests — they test internals.',
    'This is evidence method test-run (EIE §7 method 7).',
  ].join('\n'),
  detectionMethod: 'test-run: execute bun test tests/, check pass rate >= 80%.',
  fixTemplate: 'Write unit tests with real assertions. Run: bun test tests/. Fix failures.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'unit-test' },
  ],
  bulletTemplate: 'Unit test pass rate {rate}% (need >= 80%). Fix failing tests.',
  warheadTemplate: [
    '# TEST Gate: Unit Test Required',
    '',
    '## What This Gate Needs',
    'Unit test pass rate >= 80%.',
    '',
    '## How to Produce',
    'Write tests with real assertions. Run: bun test tests/',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-UNIT-TEST — test-run',
  ].join('\n'),
  evidenceSpec: { id: 'unit-test', verify: 'test-run', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['GR-TEST-FULL-SPECTRUM', 'SRE-S2-FAKE-TEST'],
  selfVerified: true,
};

export const GR_TEST_BROWSER_TEST: KnowledgeNode = {
  id: 'GR-TEST-BROWSER-TEST',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'TEST GATE — Browser Test Evidence: Browser tests must pass >= 70% (if applicable).',
    'Evidence: browser test results with pass rate >= 70%.',
    'Browser tests verify HTML/JS visual testing, DOM interactions.',
    'Not all projects require browser tests — skip if not applicable.',
    'Browser tests use headless browser automation (Puppeteer/Playwright).',
    'Tests verify visual rendering, DOM structure, user interactions.',
    'This is evidence method test-run with browser context.',
  ].join('\n'),
  detectionMethod: 'test-run: execute browser tests, check pass rate >= 70%.',
  fixTemplate: 'Write browser tests for visual/DOM features. Run in headless mode. Fix failures.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'TEST' },
    { field: 'evidenceId', op: 'equals', value: 'browser-test' },
  ],
  bulletTemplate: 'Browser test pass rate {rate}% (need >= 70%). Fix failing visual tests.',
  warheadTemplate: [
    '# TEST Gate: Browser Test Required (if applicable)',
    '',
    '## What This Gate Needs',
    'Browser test pass rate >= 70%.',
    '',
    '## How to Produce',
    'Write visual/DOM tests. Run in headless browser. Fix failures.',
    '',
    '## Reference',
    'TEST Gate — GR-TEST-BROWSER-TEST',
  ].join('\n'),
  evidenceSpec: { id: 'browser-test', verify: 'test-run', minQuality: 0.70 },
  severity: 'warn',
  layer: 5,
  links: ['GR-TEST-FULL-SPECTRUM'],
  selfVerified: true,
};

// ═══════════════════════════════════════════════════════════════
// GATE: AUDIT — Evidence: SpecAlignment, TestAuthenticity,
//        TheatricalCode, AdversarialResilience, ClaimReality, BuildOrder
// ═══════════════════════════════════════════════════════════════

export const GR_AUDIT_SPEC_ALIGNMENT: KnowledgeNode = {
  id: 'GR-AUDIT-SPEC-ALIGNMENT',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Spec Alignment Evidence: Code must match SPEC.md.',
    'Evidence: SpecAlignmentReport.json verifying code-to-spec alignment.',
    'Every component in the spec must exist in the code.',
    'Every file in the code must be referenced in the spec or manifest.',
    'No phantom components — spec describes things that don\'t exist.',
    'No undocumented code — code exists that the spec doesn\'t mention.',
    'The spec is the contract. The code is the implementation. They must align.',
  ].join('\n'),
  detectionMethod: 'fs-check + spec-read: compare spec components against actual files. Generate SpecAlignmentReport.json.',
  fixTemplate: 'Run spec alignment check. Update spec or code until they match. Save SpecAlignmentReport.json.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'spec-alignment' },
  ],
  bulletTemplate: 'Spec alignment failures: {count} mismatches. Update spec or code.',
  warheadTemplate: [
    '# AUDIT Gate: Spec Alignment Required',
    '',
    '## What This Gate Needs',
    'SpecAlignmentReport.json showing code matches spec.',
    '',
    '## How to Fix',
    'Every spec component must exist in code. Every code file must be in spec/manifest.',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-SPEC-ALIGNMENT',
  ].join('\n'),
  evidenceSpec: { id: 'spec-alignment', verify: 'spec-read', minQuality: 0.90 },
  severity: 'block',
  layer: 5,
  links: ['GR-PLAN-SPEC', 'R16-BIBLE-ENFORCEMENT', 'R22-CLAIM-REALITY'],
  selfVerified: true,
};

export const GR_AUDIT_TEST_AUTHENTICITY: KnowledgeNode = {
  id: 'GR-AUDIT-TEST-AUTHENTICITY',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Test Authenticity Evidence: Tests must be real, not theatrical.',
    'Evidence: TestAuthenticityReport.json verifying test quality.',
    'No fake tests: expect() with hardcoded literals (SRE S2).',
    'No mocks/stubs in production test paths (SRE S3).',
    'Tests must actually exercise the code, not just assert constants.',
    'A test that always passes without exercising code is theatrical.',
    'The audit verifies that tests are mechanical, not theatrical.',
  ].join('\n'),
  detectionMethod: 'sre-audit: verify 0 S2 (fake test) and S3 (mock in production) findings.',
  fixTemplate: 'Remove fake tests. Replace with real tests that exercise actual code. Run SRE.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'test-authenticity' },
  ],
  bulletTemplate: 'Test authenticity failures: {count} S2/S3 findings. Fix fake tests and mocks.',
  warheadTemplate: [
    '# AUDIT Gate: Test Authenticity Required',
    '',
    '## What This Gate Needs',
    'TestAuthenticityReport.json showing 0 fake/mock tests.',
    '',
    '## How to Fix',
    'Remove hardcoded-literal assertions. Remove production mocks. Write real tests.',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-TEST-AUTHENTICITY — S2/S3',
  ].join('\n'),
  evidenceSpec: { id: 'test-authenticity', verify: 'sre-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['IL18-THEATRICAL-CODE-ZERO', 'SRE-S2-FAKE-TEST', 'SRE-S3-MOCK-IN-PROD'],
  selfVerified: true,
};

export const GR_AUDIT_THEATRICAL_CODE: KnowledgeNode = {
  id: 'GR-AUDIT-THEATRICAL-CODE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Theatrical Code Evidence: Zero theatrical code patterns.',
    'Evidence: TheatricalCodeReport.json verifying 0 theatrical findings.',
    'No functions returning completion without side effects (S1).',
    'No empty/swallowing catches (S5).',
    'No ungrounded evidence claims (S4).',
    'Theatrical code is the antithesis of runtime-grade engineering.',
    'Zero tolerance — every instance is CRITICAL.',
  ].join('\n'),
  detectionMethod: 'sre-audit: verify 0 S1/S4/S5 findings. Scan for theatrical patterns.',
  fixTemplate: 'Run SRE. Fix every theatrical pattern. Re-run until 0 findings.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'theatrical-code' },
  ],
  bulletTemplate: 'Theatrical code: {count} S1/S4/S5 findings. Remove all theatrical patterns.',
  warheadTemplate: [
    '# AUDIT Gate: Theatrical Code Report Required',
    '',
    '## What This Gate Needs',
    'TheatricalCodeReport.json showing 0 theatrical findings.',
    '',
    '## How to Fix',
    'Remove: fake returns (S1), ungrounded claims (S4), swallowing catches (S5).',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-THEATRICAL-CODE — S1/S4/S5',
  ].join('\n'),
  evidenceSpec: { id: 'theatrical-code', verify: 'sre-audit', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL18-THEATRICAL-CODE-ZERO', 'P11-OUTPUT-IS-THE-WORK'],
  selfVerified: true,
};

export const GR_AUDIT_ADVERSARIAL: KnowledgeNode = {
  id: 'GR-AUDIT-ADVERSARIAL',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Adversarial Resilience Evidence: Security analysis must pass.',
    'Evidence: AdversarialResilienceReport.json verifying security posture.',
    '5 prompt injection categories checked (AST-based).',
    '5 enforcement gaming patterns checked.',
    'Supply chain analysis (blast radius, circular deps).',
    'Capability models (filesystem, network, process, env).',
    'No injection vectors, no gaming patterns, no supply chain risks.',
  ].join('\n'),
  detectionMethod: 'rge-audit + security scan: check injection, gaming, supply chain, capability.',
  fixTemplate: 'Run adversarial scan. Fix injection vectors. Remove gaming patterns. Verify supply chain.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'adversarial-resilience' },
  ],
  bulletTemplate: 'Adversarial resilience failures: {count} issues. Fix injection/gaming/supply-chain.',
  warheadTemplate: [
    '# AUDIT Gate: Adversarial Resilience Required',
    '',
    '## What This Gate Needs',
    'AdversarialResilienceReport.json showing no security issues.',
    '',
    '## Checks',
    '- Prompt injection (5 categories)',
    '- Enforcement gaming (5 patterns)',
    '- Supply chain (blast radius, circular deps)',
    '- Capability models (fs, network, process, env)',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-ADVERSARIAL — R20',
  ].join('\n'),
  evidenceSpec: { id: 'adversarial-resilience', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'block',
  layer: 5,
  links: ['R20-ADVERSARIAL-RESILIENCE', 'KB06-INJECTION'],
  selfVerified: true,
};

export const GR_AUDIT_CLAIM_REALITY: KnowledgeNode = {
  id: 'GR-AUDIT-CLAIM-REALITY',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Claim-Reality Evidence: All claims must match reality.',
    'Evidence: ClaimRealityReport.json comparing claims to filesystem/tests/RGE.',
    'Component 1: FILESYSTEM DIFF — Merkle before/after snapshot.',
    'Component 2: TEST EXECUTION — before/after test comparison.',
    'Component 3: RGE SCORING — before/after violation comparison.',
    'The agent cannot rephrase reality. The filesystem changed or it didn\'t.',
    'If claims don\'t match reality, the evidence is fabricated.',
  ].join('\n'),
  detectionMethod: 'claim-reality: compare agent claims against filesystem diff, test results, RGE scores.',
  fixTemplate: 'Run claim-reality verification. All three components must show the claimed work.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'claim-reality' },
  ],
  bulletTemplate: 'Claim-reality mismatch: claims don\'t match {component}. Fix the work, not the claim.',
  warheadTemplate: [
    '# AUDIT Gate: Claim-Reality Required',
    '',
    '## What This Gate Needs',
    'ClaimRealityReport.json showing claims match reality.',
    '',
    '## Triple Verification',
    '1. FILESYSTEM: Merkle diff shows claimed changes.',
    '2. TESTS: Pass rate matches claimed improvements.',
    '3. RGE: Violation count matches claimed fixes.',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-CLAIM-REALITY — R22 — IL15',
  ].join('\n'),
  evidenceSpec: { id: 'claim-reality', verify: 'claim-reality', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'IL15-EVIDENCE-TRIPLE-RULE', 'R22-CLAIM-REALITY'],
  selfVerified: true,
};

export const GR_AUDIT_BUILD_ORDER: KnowledgeNode = {
  id: 'GR-AUDIT-BUILD-ORDER',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'AUDIT GATE — Build Order Evidence: Code follows failure-mode-first build order.',
    'Evidence: BuildOrderReport.json verifying component dependency order.',
    'Error handling exists before features depend on it.',
    'Resource cleanup exists before resources are acquired.',
    'Verification infrastructure exists before code needs verifying.',
    'The build order prevents architectural debt.',
    'The audit verifies the actual code structure matches the planned order.',
  ].join('\n'),
  detectionMethod: 'rge-audit: verify component dependencies follow failure-mode-first order.',
  fixTemplate: 'Reorder components: error handling → cleanup → verification → features.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
    { field: 'evidenceId', op: 'equals', value: 'build-order' },
  ],
  bulletTemplate: 'Build order violations: {count} dependencies in wrong order.',
  warheadTemplate: [
    '# AUDIT Gate: Build Order Required',
    '',
    '## What This Gate Needs',
    'BuildOrderReport.json showing failure-mode-first order.',
    '',
    '## Required Order',
    'Error handling → Resource cleanup → Verification → Features',
    '',
    '## Reference',
    'AUDIT Gate — GR-AUDIT-BUILD-ORDER — R21',
  ].join('\n'),
  evidenceSpec: { id: 'build-order', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'warn',
  layer: 5,
  links: ['BO-FAILURE-MODE-FIRST', 'R21-BUILD-ORDER', 'GR-PLAN-BUILD-ORDER'],
  selfVerified: true,
};

// ═══════════════════════════════════════════════════════════════
// GATE: DELIVERY — Evidence: Ship Package, Checksum, Evidence Archive,
//        Changelog, Debug Log, Build Report
// ═══════════════════════════════════════════════════════════════

export const GR_DELIVERY_SHIP_PACKAGE: KnowledgeNode = {
  id: 'GR-DELIVERY-SHIP-PACKAGE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Ship Package Evidence: dist/ must exist with content.',
    'Evidence: dist/ directory exists with index.js and all bundled assets.',
    'The ship package is the deployable artifact.',
    'dist/index.js must be >0 bytes — an empty file means build failed.',
    'The package must be self-contained — all dependencies bundled.',
    'Verification: fs-check for dist/ existence and content.',
    'This is the final product. Without it, nothing ships.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify dist/ exists, dist/index.js exists and is >0 bytes.',
  fixTemplate: 'Run: bun build src/index.ts --outdir dist --target bun --format esm --bundle. Verify output.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'ship-package' },
  ],
  bulletTemplate: 'Ship package missing: dist/ empty or nonexistent. Run bun build.',
  warheadTemplate: [
    '# DELIVERY Gate: Ship Package Required',
    '',
    '## What This Gate Needs',
    'dist/ directory with index.js and all assets.',
    '',
    '## How to Produce',
    'bun build src/index.ts --outdir dist --target bun --format esm --bundle',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-SHIP-PACKAGE',
  ].join('\n'),
  evidenceSpec: { id: 'ship-package', verify: 'fs-check', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['GR-VERIFY-BUILD', 'IL01-OUTPUT-IS-REALITY'],
  selfVerified: true,
};

export const GR_DELIVERY_CHECKSUM: KnowledgeNode = {
  id: 'GR-DELIVERY-CHECKSUM',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Checksum Evidence: SHA-256 checksum of dist/index.js.',
    'Evidence: checksum file or field with sha256 hash of the bundle.',
    'The checksum verifies the ship package was not tampered with.',
    'Container deployment verifies the checksum matches.',
    'Without a checksum, there is no integrity guarantee for the deployed artifact.',
    'The checksum is generated by the shark-deliver tool.',
    'This is the cryptographic proof of the artifact.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify checksum file exists with valid sha256 hash matching dist/index.js.',
  fixTemplate: 'Run: sha256sum dist/index.js > dist/checksum.txt. Verify the hash.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'checksum' },
  ],
  bulletTemplate: 'Checksum missing. Generate: sha256sum dist/index.js.',
  warheadTemplate: [
    '# DELIVERY Gate: Checksum Required',
    '',
    '## What This Gate Needs',
    'SHA-256 checksum of dist/index.js.',
    '',
    '## How to Produce',
    'sha256sum dist/index.js > dist/checksum.txt',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-CHECKSUM',
  ].join('\n'),
  evidenceSpec: { id: 'checksum', verify: 'fs-check', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['GR-DELIVERY-SHIP-PACKAGE', 'R05-CONTAINER-DEPLOY'],
  selfVerified: true,
};

export const GR_DELIVERY_EVIDENCE_ARCHIVE: KnowledgeNode = {
  id: 'GR-DELIVERY-EVIDENCE-ARCHIVE',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Evidence Archive Evidence: All gate evidence collected.',
    'Evidence: archive directory or zip with all evidence files.',
    'Includes: SPEC.md, FileManifest.json, test results, audit reports.',
    'The evidence archive is the complete proof of the build process.',
    'It allows post-hoc verification of every gate.',
    'Without the archive, there is no auditable trail.',
    'The shark-deliver tool auto-collects the archive.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify evidence archive directory exists with all required evidence files.',
  fixTemplate: 'Collect all evidence files into .shark/evidence/ or equivalent archive directory.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'evidence-archive' },
  ],
  bulletTemplate: 'Evidence archive incomplete: missing {files}. Collect all gate evidence.',
  warheadTemplate: [
    '# DELIVERY Gate: Evidence Archive Required',
    '',
    '## What This Gate Needs',
    'Complete archive of all gate evidence.',
    '',
    '## Required Files',
    '- SPEC.md, FileManifest.json',
    '- Test results (Container, Unit, Browser)',
    '- Audit reports (Spec, Test, Theatrical, Adversarial)',
    '- Checksum, Build Report',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-EVIDENCE-ARCHIVE',
  ].join('\n'),
  evidenceSpec: { id: 'evidence-archive', verify: 'fs-check', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['IL15-EVIDENCE-TRIPLE-RULE', 'GR-DELIVERY-SHIP-PACKAGE'],
  selfVerified: true,
};

export const GR_DELIVERY_CHANGELOG: KnowledgeNode = {
  id: 'GR-DELIVERY-CHANGELOG',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Changelog Evidence: CHANGELOG.md must document changes.',
    'Evidence: CHANGELOG.md with version, date, and change list.',
    'The changelog provides human-readable context for the release.',
    'Each change must reference the component affected.',
    'Breaking changes must be clearly marked.',
    'The changelog is part of the delivery package.',
    'Without it, consumers don\'t know what changed.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify CHANGELOG.md exists with version and change entries.',
  fixTemplate: 'Create CHANGELOG.md: ## [version] - date\\n- Change 1\\n- Change 2',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'changelog' },
  ],
  bulletTemplate: 'CHANGELOG.md missing. Document version, date, and changes.',
  warheadTemplate: [
    '# DELIVERY Gate: Changelog Required',
    '',
    '## What This Gate Needs',
    'CHANGELOG.md with version, date, and change list.',
    '',
    '## Format',
    '## [version] - YYYY-MM-DD',
    '- Added: ...',
    '- Changed: ...',
    '- Fixed: ...',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-CHANGELOG',
  ].join('\n'),
  evidenceSpec: { id: 'changelog', verify: 'fs-check', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['GR-DELIVERY-SHIP-PACKAGE'],
  selfVerified: true,
};

export const GR_DELIVERY_DEBUG_LOG: KnowledgeNode = {
  id: 'GR-DELIVERY-DEBUG-LOG',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Debug Log Evidence: DEBUG_LOG.md must capture the build process.',
    'Evidence: DEBUG_LOG.md with build steps, errors encountered, and resolutions.',
    'The debug log provides a traceable record of the development process.',
    'It captures decisions made, errors hit, and how they were resolved.',
    'This is invaluable for post-hoc debugging and knowledge transfer.',
    'The debug log is part of the delivery package.',
    'It should be chronological and detailed.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify DEBUG_LOG.md exists with build process documentation.',
  fixTemplate: 'Create DEBUG_LOG.md documenting each build step, error, and resolution.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'debug-log' },
  ],
  bulletTemplate: 'DEBUG_LOG.md missing. Document build steps, errors, resolutions.',
  warheadTemplate: [
    '# DELIVERY Gate: Debug Log Required',
    '',
    '## What This Gate Needs',
    'DEBUG_LOG.md with chronological build process documentation.',
    '',
    '## Content',
    '- Build steps taken',
    '- Errors encountered and resolved',
    '- Key decisions and rationale',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-DEBUG-LOG',
  ].join('\n'),
  evidenceSpec: { id: 'debug-log', verify: 'fs-check', minQuality: 0.75 },
  severity: 'warn',
  layer: 5,
  links: ['GR-DELIVERY-CHANGELOG'],
  selfVerified: true,
};

export const GR_DELIVERY_BUILD_REPORT: KnowledgeNode = {
  id: 'GR-DELIVERY-BUILD-REPORT',
  source: 'rg-standards',
  sourceFile: 'EIE_DESIGN_SPEC.md',
  category: 'gate-requirement',
  rule: [
    'DELIVERY GATE — Build Report Evidence: BUILD_REPORT.md must summarize the build.',
    'Evidence: BUILD_REPORT.md with metrics, test results, and audit summary.',
    'The build report is the executive summary of the entire build process.',
    'It includes: line counts, bundle size, test pass rates, audit findings.',
    'It provides a single-page overview of the project status.',
    'The build report is part of the delivery package.',
    'It should be concise but comprehensive.',
  ].join('\n'),
  detectionMethod: 'fs-check: verify BUILD_REPORT.md exists with build metrics and summary.',
  fixTemplate: 'Create BUILD_REPORT.md: metrics table, test results, audit summary, delivery status.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'DELIVERY' },
    { field: 'evidenceId', op: 'equals', value: 'build-report' },
  ],
  bulletTemplate: 'BUILD_REPORT.md missing. Summarize metrics, tests, audit results.',
  warheadTemplate: [
    '# DELIVERY Gate: Build Report Required',
    '',
    '## What This Gate Needs',
    'BUILD_REPORT.md with build metrics and summary.',
    '',
    '## Content',
    '- Source lines, bundle size',
    '- Test pass rates (container, unit, browser)',
    '- Audit findings (0 critical)',
    '- Delivery status: SHIP/FAIL',
    '',
    '## Reference',
    'DELIVERY Gate — GR-DELIVERY-BUILD-REPORT',
  ].join('\n'),
  evidenceSpec: { id: 'build-report', verify: 'fs-check', minQuality: 0.80 },
  severity: 'block',
  layer: 5,
  links: ['GR-DELIVERY-SHIP-PACKAGE', 'GR-DELIVERY-EVIDENCE-ARCHIVE'],
  selfVerified: true,
};

// EXPORTS
export const gateRequirements: KnowledgeNode[] = [
  // PLAN
  GR_PLAN_SPEC,
  GR_PLAN_GUARDIAN,
  GR_PLAN_ARCHITECTURE,
  GR_PLAN_ERROR_STRATEGY,
  GR_PLAN_BUILD_ORDER,
  GR_PLAN_SCOPE,
  // BUILD
  GR_BUILD_FILE_MANIFEST,
  GR_BUILD_GIT_DIFF,
  GR_BUILD_TYPE_SAFETY,
  GR_BUILD_ERROR_HANDLING,
  GR_BUILD_RESOURCE_CLEANUP,
  GR_BUILD_ANTI_THEATRICAL,
  // VERIFY
  GR_VERIFY_TSC,
  GR_VERIFY_BUILD,
  GR_VERIFY_RGE_SCORE,
  GR_VERIFY_SRE_SCORE,
  GR_VERIFY_TYPE_CONTRACT,
  GR_VERIFY_IMPORT_VALIDITY,
  // TEST
  GR_TEST_CONTAINER_SPAWN,
  GR_TEST_CONTAINER_TEST,
  GR_TEST_TUI_INTERACTION,
  GR_TEST_FULL_SPECTRUM,
  GR_TEST_UNIT_TEST,
  GR_TEST_BROWSER_TEST,
  // AUDIT
  GR_AUDIT_SPEC_ALIGNMENT,
  GR_AUDIT_TEST_AUTHENTICITY,
  GR_AUDIT_THEATRICAL_CODE,
  GR_AUDIT_ADVERSARIAL,
  GR_AUDIT_CLAIM_REALITY,
  GR_AUDIT_BUILD_ORDER,
  // DELIVERY
  GR_DELIVERY_SHIP_PACKAGE,
  GR_DELIVERY_CHECKSUM,
  GR_DELIVERY_EVIDENCE_ARCHIVE,
  GR_DELIVERY_CHANGELOG,
  GR_DELIVERY_DEBUG_LOG,
  GR_DELIVERY_BUILD_REPORT,
];
