/**
 * src/eie/nodes/index.ts — Barrel Export for EIE Knowledge Nodes
 *
 * Exports all knowledge nodes from the EIE knowledge graph.
 * The combined ALL_KNOWLEDGE_NODES array is the complete set of
 * nodes used by the context matcher, bullet generator, and
 * warhead generator.
 *
 * Categories:
 *   principles (50) + iron-laws (22) + gate-requirements (36) +
 *   anti-patterns (80) + analysis-orders (6) + failure-patterns (20) +
 *   fix-patterns (80) + testing (35) + security (36) + typescript (44) +
 *   concurrency (30) + async-concurrency (30) +
 *   persistence (15) + gate-knowledge (36) +
 *   error-recovery (50) + architecture (35) + nlp-component (15) +
 *   build-order (10) + enforcement (15) + data-validation (35) +
 *   docker-container (35) + llm-agent-runtime (40) +
 *   domain-specific (130) + ci-cd-pipeline (35)
 *   Total: 1000 nodes
 */

import type { KnowledgeNode } from '../types';

// ── Principles (P1-P12) ────────────────────────────────────────
export {
  P1_DEFENSIVE_IMPORT, P2_TYPE_CERTAINTY, P3_ERROR_COMPLETENESS,
  P4_RESOURCE_LIFECYCLE, P5_ATOMIC_STATE, P6_DEPENDENCY_CHECK,
  P7_PATH_RESOLUTION, P8_CONFIG_VALIDATION, P9_ASYNC_DISCIPLINE,
  P10_OUTPUT_CONTRACT, P11_OUTPUT_IS_THE_WORK, P12_EMPTY_STATE_GUARD,
  principles,
} from './principles';

// ── Iron Laws (IL01-IL22) ──────────────────────────────────────
export {
  IL01_OUTPUT_IS_REALITY, IL02_CONTRACT_HONORED, IL03_ASYNC_COMPLETENESS,
  IL04_NO_SILENT_FAILURE, IL05_ATOMIC_TRANSITION, IL06_RESOURCE_OWNERSHIP,
  IL07_ENVIRONMENT_INDEPENDENCE, IL08_FAIL_FAST_CONFIG, IL09_WIRE_DONT_DECLARE,
  IL10_EVIDENCE_IS_MECHANICAL, IL11_OUTPUT_IS_PROOF, IL12_EMPTY_IS_NOT_SUCCESS,
  IL13_RULE_OWNERSHIP_EXCLUSIVE, IL14_ANALYSIS_ORDER_MATTERS,
  IL15_EVIDENCE_TRIPLE_RULE, IL16_DERAILMENT_FIVE_SIGNALS,
  IL17_ESCALATION_CUMULATIVE, IL18_THEATRICAL_CODE_ZERO,
  IL19_GATE_ORDER_IMMUTABLE, IL20_COMPACTION_PRESERVES_STATE,
  IL21_BULLET_BEFORE_THROW, IL22_PROGRESSIVE_DISCLOSURE,
  ironLaws,
} from './iron-laws';

// ── Gate Requirements (36 nodes) ───────────────────────────────
export {
  GR_PLAN_SPEC, GR_PLAN_GUARDIAN, GR_PLAN_ARCHITECTURE,
  GR_PLAN_ERROR_STRATEGY, GR_PLAN_BUILD_ORDER, GR_PLAN_SCOPE,
  GR_BUILD_FILE_MANIFEST, GR_BUILD_GIT_DIFF, GR_BUILD_TYPE_SAFETY,
  GR_BUILD_ERROR_HANDLING, GR_BUILD_RESOURCE_CLEANUP, GR_BUILD_ANTI_THEATRICAL,
  GR_VERIFY_TSC, GR_VERIFY_BUILD, GR_VERIFY_RGE_SCORE,
  GR_VERIFY_SRE_SCORE, GR_VERIFY_TYPE_CONTRACT, GR_VERIFY_IMPORT_VALIDITY,
  GR_TEST_CONTAINER_SPAWN, GR_TEST_CONTAINER_TEST, GR_TEST_TUI_INTERACTION,
  GR_TEST_FULL_SPECTRUM, GR_TEST_UNIT_TEST, GR_TEST_BROWSER_TEST,
  GR_AUDIT_SPEC_ALIGNMENT, GR_AUDIT_TEST_AUTHENTICITY, GR_AUDIT_THEATRICAL_CODE,
  GR_AUDIT_ADVERSARIAL, GR_AUDIT_CLAIM_REALITY, GR_AUDIT_BUILD_ORDER,
  GR_DELIVERY_SHIP_PACKAGE, GR_DELIVERY_CHECKSUM, GR_DELIVERY_EVIDENCE_ARCHIVE,
  GR_DELIVERY_CHANGELOG, GR_DELIVERY_DEBUG_LOG, GR_DELIVERY_BUILD_REPORT,
  gateRequirements,
} from './gate-requirements';

// ── Anti-Patterns (80 nodes) ───────────────────────────────────
export {
  AP_THEATRICAL_CODE, AP_FAKE_TEST, AP_MOCK_IN_PRODUCTION,
  AP_UNGROUNDED_CLAIM, AP_EMPTY_CATCH, AP_UNSAFE_CAST,
  AP_FLOATING_PROMISE, AP_UNCLEANED_INTERVAL, AP_HARDCODED_PATH,
  AP_UNVALIDATED_CONFIG, AP_OPENCODE_RUN, AP_DIRECT_SCRIPT,
  AP_STATIC_GREP, AP_TEXT_MATCHING, AP_IDENTITY_SPOOFING,
  AP_TOOL_BLOCKING_BYPASS, AP_SCOPE_CREEP, AP_SIMPLIFICATION,
  AP_CONFUSION, AP_IMPATIENCE, AP_DEAD_EXPORT,
  AP_DUPLICATE_ENFORCEMENT, AP_EVIDENCE_FABRICATION, AP_EMPTY_STATE_FALSE_POSITIVE,
  AP_REPEATED_VIOLATION, AP_SELF_REFERENCE, AP_PRIVILEGE_ESCALATION,
  AP_CONTAINER_ESCAPE, AP_NETWORK_EGRESS, AP_FABRICATION,
  AP_ASSUMPTION, AP_UNDERMINING, AP_TORN_STATE,
  AP_RETURN_NULL_NONNULL, AP_HOST_FALLBACK, AP_SUCCESS_CLAIM,
  AP_MODEL_RESTRICTION, AP_MOCK_STUB, AP_CROSS_SOURCE_CONTAMINATION,
  AP_ENV_VAR_BYPASS,
  AP_RETRY_WITHOUT_CHANGE, AP_GOD_FUNCTION, AP_NESTED_PROMISE,
  AP_CALLBACK_HELL, AP_SYNC_IN_ASYNC, AP_UNHANDLED_PROMISE_REJECTION,
  AP_MUTABLE_SHARED_STATE, AP_IMPLICIT_DEPENDENCY, AP_MAGIC_STRING,
  AP_DEEP_NESTING, AP_LONG_PARAMETER_LIST, AP_FEATURE_ENVY,
  AP_SHOTGUN_SURGERY, AP_DIVERGENT_CHANGE, AP_PRIMITIVE_OBSESSION,
  AP_DATA_CLUMPS, AP_SPECULATIVE_GENERALITY, AP_ODDBALL_SOLUTION,
  AP_TEMPORARY_FIELD, AP_MESSAGE_CHAIN,
  AP_DEAD_CODE, AP_DUPLICATE_CODE, AP_EXCESSIVE_RETURN,
  AP_BOOLEAN_FLAG_PARAM, AP_UNSUPPORTED_OPERATION, AP_EMPTY_INTERFACE,
  AP_ABSTRACT_WITHOUT_IMPL, AP_EXCESSIVE_MAPPING, AP_CHAIN_OF_COMMAND,
  AP_MIDDLE_MAN, AP_INAPPROPRIATE_INTIMACY, AP_REFUSED_BEQUEST,
  AP_DATA_CLASS, AP_LAZY_CLASS, AP_COMMENTS_AS_CODE,
  AP_FLAG_ARGUMENT, AP_EXPLICIT_THIS, AP_SYNC_VIOLATION,
  AP_LEAKY_ABSTRACTION, AP_CONTRIVED_COMPLEXITY,
  antiPatterns,
} from './anti-patterns';

// ── Analysis Orders (6 nodes) ──────────────────────────────────
export {
  AO0_PASS_THROUGH, AO1_REGEX_CANDIDATE, AO2_AST_WALKER,
  AO3_TYPECHECKER, AO4_CFG_DFA, AO5_EXECUTION_VERIFICATION,
  analysisOrders,
} from './analysis-orders';

// ── Failure Patterns (20 nodes) ────────────────────────────────
export {
  FM01_LOAD_TIME_CRASH, FM02_SILENT_DATA_CORRUPTION, FM03_RESOURCE_LEAK,
  FM04_TORN_STATE, FM05_UNHANDLED_REJECTION, FM06_TYPE_CONFUSION,
  FM07_ENVIRONMENT_DEPENDENCY, FM08_CONFIG_INJECTION, FM09_THEATRICAL_COMPLETION,
  FM10_VACUOUS_VALIDATION, FM11_EVIDENCE_FABRICATION, FM12_DEAD_CODE,
  FM13_SCOPE_CREEP, FM14_FAKE_TEST, FM15_CONCURRENT_MODIFICATION,
  FM16_CONFIGURATION_DRIFT, FM17_INFINITE_LOOP, FM18_ZOMBIE_TIMER,
  FM19_NULL_DEREFERENCE, FM20_PROMISE_SERIAL,
  failurePatterns,
} from './failure-patterns';

// ── Fix Patterns (80 nodes) ────────────────────────────────────
export {
  FX01_FIX_THEATRICAL_CODE, FX02_FIX_FAKE_TEST, FX03_FIX_EMPTY_CATCH,
  FX04_FIX_UNSAFE_CAST, FX05_FIX_FLOATING_PROMISE, FX06_FIX_UNCLEANED_INTERVAL,
  FX07_FIX_HARDCODED_PATH, FX08_FIX_UNVALIDATED_CONFIG, FX09_FIX_TORN_STATE,
  FX10_FIX_DEAD_EXPORT, FX11_FIX_UNGROUNDED_CLAIM, FX12_FIX_MOCK_IN_PROD,
  FX13_FIX_OPENCODE_RUN, FX14_FIX_DIRECT_SCRIPT, FX15_FIX_STATIC_GREP,
  FX16_FIX_TEXT_MATCHING, FX17_FIX_SCOPE_CREEP, FX18_FIX_DUPLICATE_ENFORCEMENT,
  FX19_FIX_EVIDENCE_FABRICATION, FX20_FIX_EMPTY_STATE,
  FX21_FIX_RETURN_NULL, FX22_FIX_HOST_FALLBACK, FX23_FIX_SUCCESS_CLAIM,
  FX24_FIX_ENV_VAR_BYPASS, FX25_FIX_TOOL_BYPASS, FX26_FIX_PRIVILEGE_ESCALATION,
  FX27_FIX_CONTAINER_ESCAPE, FX28_FIX_NETWORK_EGRESS, FX29_FIX_SELF_REFERENCE,
  FX30_FIX_MODEL_RESTRICTION, FX31_FIX_SIMPLIFICATION, FX32_FIX_CONFUSION,
  FX33_FIX_IMPATIENCE, FX34_FIX_ASSUMPTION, FX35_FIX_UNDERMINING,
  FX36_FIX_FABRICATION, FX37_FIX_MOCK_STUB, FX38_FIX_CROSS_SOURCE,
  FX39_FIX_IDENTITY_SPOOFING, FX40_FIX_REPEATED_VIOLATION,
  FX41_FIX_RETRY_WITH_CHANGE, FX42_FIX_GOD_FUNCTION, FX43_FIX_NESTED_PROMISE,
  FX44_FIX_CALLBACK_HELL, FX45_FIX_SYNC_IN_ASYNC, FX46_FIX_UNHANDLED_REJECTION,
  FX47_FIX_MUTABLE_SHARED, FX48_FIX_IMPLICIT_DEP, FX49_FIX_MAGIC_STRING,
  FX50_FIX_DEEP_NESTING, FX51_FIX_LONG_PARAMS, FX52_FIX_FEATURE_ENVY,
  FX53_FIX_SHOTGUN_SURGERY, FX54_FIX_DIVERGENT_CHANGE, FX55_FIX_PRIMITIVE_OBSESSION,
  FX56_FIX_DATA_CLUMPS, FX57_FIX_SPECULATIVE_GENERALITY, FX58_FIX_ODDBALL_SOLUTION,
  FX59_FIX_TEMPORARY_FIELD, FX60_FIX_MESSAGE_CHAIN,
  FX61_FIX_DEAD_CODE, FX62_FIX_DUPLICATE_CODE, FX63_FIX_EXCESSIVE_RETURN,
  FX64_FIX_BOOLEAN_FLAG_PARAM, FX65_FIX_UNSUPPORTED_OPERATION, FX66_FIX_EMPTY_INTERFACE,
  FX67_FIX_ABSTRACT_WITHOUT_IMPL, FX68_FIX_EXCESSIVE_MAPPING, FX69_FIX_CHAIN_OF_COMMAND,
  FX70_FIX_MIDDLE_MAN, FX71_FIX_INAPPROPRIATE_INTIMACY, FX72_FIX_REFUSED_BEQUEST,
  FX73_FIX_DATA_CLASS, FX74_FIX_LAZY_CLASS, FX75_FIX_COMMENTS_AS_CODE,
  FX76_FIX_FLAG_ARGUMENT, FX77_FIX_EXPLICIT_THIS, FX78_FIX_SYNC_VIOLATION,
  FX79_FIX_LEAKY_ABSTRACTION, FX80_FIX_CONTRIVED_COMPLEXITY,
  fixPatterns,
} from './fix-patterns';

// ── Testing Nodes (35 nodes) ───────────────────────────────────
export {
  TEST_PROPERTY_BASED, TEST_MUTATION_THRESHOLD, TEST_COVERAGE_THRESHOLD,
  TEST_CONTAINER_TUI, TEST_FORBIDDEN_METHODS, TEST_EVIDENCE_REQUIREMENTS,
  TEST_MECHANICAL_VERIFICATION,
  TEST_NEGATIVE_INPUT, TEST_NEGATIVE_BOUNDARY, TEST_NEGATIVE_ERROR,
  TEST_NEGATIVE_SECURITY, TEST_NEGATIVE_CONCURRENCY,
  TEST_CONFIG_DIFF, TEST_DIFFERENTIAL, TEST_METAMORPHIC, TEST_FLAKY_DETECTION,
  TEST_SNAPSHOT_DISCIPLINE, TEST_INTEGRATION_BOUNDARY, TEST_TEST_ISOLATION,
  TEST_ASSERTION_QUALITY, TEST_PERFORMANCE_BUDGET, TEST_TEARDOWN_COMPLETENESS,
  TEST_DETERMINISM, TEST_DATA_FACTORIES, TEST_ERROR_MESSAGE_QUALITY,
  TEST_FUZZ_TESTING, TEST_REGRESSION_TESTING, TEST_SMOKE_TESTING,
  TEST_INTEGRATION_TESTING, TEST_E2E_TESTING, TEST_CONTRACT_TESTING,
  TEST_SNAPSHOT_TESTING, TEST_GOLDEN_MASTER, TEST_CHAOS_TESTING, TEST_LOAD_TESTING,
  testingNodes,
} from './testing-nodes';

// ── Security Nodes (36 nodes) ──────────────────────────────────
export {
  SEC_INJECTION_DIRECT, SEC_INJECTION_INDIRECT, SEC_INJECTION_TEMPLATE,
  SEC_INJECTION_TOOL, SEC_INJECTION_ENCODING,
  SEC_GAMING_BYPASS, SEC_GAMING_WEAKENING, SEC_GAMING_DISABLE,
  SEC_GAMING_SPOOF, SEC_GAMING_REPLAY,
  SEC_SUPPLY_BLAST_RADIUS, SEC_SUPPLY_CYCLES, SEC_SUPPLY_INTEGRITY,
  SEC_CAPABILITY_FS, SEC_CAPABILITY_NETWORK, SEC_CAPABILITY_PROCESS,
  SEC_CAPABILITY_ENV, SEC_CAPABILITY_MEMORY,
  SEC_INFO_FLOW_LATTICE, SEC_INFO_FLOW_TAINT,
  SEC_REDTIME_FUZZ, SEC_CROSS_DETECTOR, SEC_SANDBOX_ISOLATION,
  SEC_NETWORK_MODEL, SEC_TIMING_ATTACK, SEC_AUDIT_TRAIL,
  SEC_ADVANCED_TIMING_ATTACK, SEC_ADVANCED_SIDE_CHANNEL, SEC_ADVANCED_DESERIALIZATION,
  SEC_ADVANCED_XXE, SEC_ADVANCED_SSRF, SEC_ADVANCED_TEMPLATE_INJECTION,
  SEC_ADVANCED_LDAP_INJECTION, SEC_ADVANCED_XPATH_INJECTION,
  SEC_ADVANCED_LOG_INJECTION, SEC_ADVANCED_OPEN_REDIRECT,
  securityNodes,
} from './security-nodes';

// ── TypeScript Nodes (44 nodes) ────────────────────────────────
export {
  TS_COMPILER_PROGRAM, TS_COMPILER_CHECKER, TS_COMPILER_HOST,
  TS_COMPILER_OPTIONS, TS_SOURCE_FILE_PARSE,
  TS_CHECKER_TYPE_AT_LOC, TS_CHECKER_ASSIGNABLE, TS_CHECKER_SYMBOL,
  TS_CHECKER_SIGNATURE, TS_CHECKER_PROPS,
  TS_AST_FOREACH_CHILD, TS_AST_GUARDS, TS_AST_PARENT, TS_AST_FACTORY,
  TS_SYMBOL_EXPORTS, TS_SYMBOL_ALIASES, TS_SYMBOL_DECLARATIONS, TS_SYMBOL_TYPE_FLAGS,
  TS_SF_NO_ANY, TS_SF_NO_ASYNCEXT, TS_SF_ERROR_RETURN, TS_SF_IMPORT_GUARD,
  TS_SF_CLEANUP_PAIRED, TS_SF_NO_HARD_PATH, TS_SF_HANDLE_ZERO,
  TS_PRINTER, TS_TRANSFORM, TS_DIAGNOSTICS, TS_GENERIC_CONSTRAINTS, TS_CONDITIONAL_TYPES,
  TS_ADVANCED_CONDITIONAL_TYPES, TS_ADVANCED_MAPPED_TYPES, TS_ADVANCED_TEMPLATE_LITERAL,
  TS_ADVANCED_KEYOF, TS_ADVANCED_INSTANCEOF, TS_ADVANCED_TYPE_GUARD, TS_ADVANCED_TYPE_ASSERTION,
  TS_ADVANCED_DECORATORS, TS_ADVANCED_MIXINS, TS_ADVANCED_GENERATORS, TS_ADVANCED_ITERATORS,
  TS_ADVANCED_PROXY, TS_ADVANCED_REFLECT, TS_ADVANCED_SYMBOL,
  typescriptNodes,
} from './typescript-nodes';

// ── Concurrency Nodes (30 nodes) ───────────────────────────────
export {
  CONC_ACTOR_MODEL, CONC_MESSAGE_PASSING, CONC_ACTOR_LIFECYCLE,
  CONC_WORKER_POOL, CONC_QUEUE_BACKPRESSURE,
  CONC_PRIORITY_QUEUE,
  CONC_TOKEN_BUCKET,
  CONC_CIRCUIT_BREAKER, CONC_CIRCUIT_STATES,
  CONC_EXP_BACKOFF, CONC_RETRY_BUDGET,
  CONC_NURSERY, CONC_PROMISE_ALL,
  CONC_PROCESS_EXEC,
  CONC_RESOURCE_BUDGET, CONC_DEADLOCK_PREVENTION,
  CONC_ASYNC_ITERATOR,
  CONC_WORKER_THREAD, CONC_BACKPRESSURE_PIPE, CONC_ASYNC_SEMAPHORE,
  CONC_ACTOR_MODEL_ADVANCED, CONC_STM, CONC_CSP, CONC_DATAFLOW,
  CONC_FUTURES_PROMISES, CONC_REACTIVE_STREAMS, CONC_EVENT_SOURCING_CONC,
  CONC_LOCK_FREE, CONC_WAIT_FREE, CONC_MEMOIZATION_CONC,
  concurrencyNodes,
} from './concurrency-nodes';

// ── Persistence Nodes (13 nodes) ───────────────────────────────
export {
  PERSIST_SQLITE_WAL, PERSIST_SQLITE_MIGRATION,
  PERSIST_MERKLE_CHAIN, PERSIST_MERKLE_TREE, PERSIST_MERKLE_VERIFY,
  PERSIST_EVENT_SOURCING, PERSIST_EVENT_REPLAY,
  PERSIST_APPEND_ONLY, PERSIST_LOG_ROTATION,
  PERSIST_CONTENT_ADDRESS, PERSIST_CONTENT_DEDUP,
  PERSIST_MYERS_DIFF,
  PERSIST_EVIDENCE_COLLECT,
  persistenceNodes,
} from './persistence-nodes';

// ── Gate Knowledge Nodes (36 nodes) ────────────────────────────
export {
  GK_PLAN_7Q, GK_PLAN_BUILD_ORDER, GK_PLAN_SCOPE,
  GK_PLAN_SPEC_TEMPLATE, GK_PLAN_DEPS, GK_PLAN_CONFIG,
  GK_BUILD_P1_P10, GK_BUILD_ERROR_HANDLING, GK_BUILD_TYPE_SAFETY,
  GK_BUILD_RESOURCE_LIFECYCLE, GK_BUILD_ANTI_THEATRICAL, GK_BUILD_EMPTY_STATE,
  GK_VERIFY_TSC, GK_VERIFY_BUILD, GK_VERIFY_RGE,
  GK_VERIFY_SRE, GK_VERIFY_TYPECHECKER, GK_VERIFY_EVIDENCE,
  GK_TEST_CONTAINER_BIBLE, GK_TEST_FORBIDDEN, GK_TEST_EVIDENCE_REQ,
  GK_TEST_MECHANICAL, GK_TEST_NEGATIVE, GK_TEST_CHECKSUM,
  GK_AUDIT_22_LAYER, GK_AUDIT_ADVERSARIAL, GK_AUDIT_CLAIM_REALITY,
  GK_AUDIT_BIBLE, GK_AUDIT_SPEC_FIDELITY, GK_AUDIT_BUILD_ORDER,
  GK_DELIVERY_SHIP_PKG, GK_DELIVERY_CHECKSUM, GK_DELIVERY_EVIDENCE_ARCHIVE,
  GK_DELIVERY_SPEC_FIDELITY, GK_DELIVERY_CHANGELOG, GK_DELIVERY_DEBUG_LOG,
  gateKnowledge,
} from './gate-knowledge';

// ── Error Recovery Nodes (50 nodes) ────────────────────────────
export {
  ERR_TS2322, ERR_TS2304, ERR_TS2339, ERR_TS2559, ERR_TS2307,
  ERR_TS2345, ERR_TS2531, ERR_TS2532, ERR_TS2588, ERR_TS2769,
  ERR_TS18046, ERR_TS18048, ERR_TS2349, ERR_TS2351, ERR_TS2454,
  ERR_TS2324, ERR_TS2314, ERR_TS2416, ERR_TS2554, ERR_TS2533,
  ERR_BUILD_MISSING_MODULE, ERR_BUILD_CIRCULAR_DEP, ERR_BUILD_SYNTAX_ERROR,
  ERR_BUILD_EXPORT_MISSING, ERR_BUILD_TYPE_ERROR,
  ERR_BUILD_DUPLICATE_DECL, ERR_BUILD_IMPORT_TYPE, ERR_BUILD_NO_ENTRY,
  ERR_BUILD_CONFIG, ERR_BUILD_PERMISSION,
  ERR_RT_UNDEFINED_FN, ERR_RT_CANNOT_READ, ERR_RT_MAX_CALL_STACK,
  ERR_RT_HEAP_OOM, ERR_RT_UNHANDLED_REJECTION,
  ERR_RT_ENOENT, ERR_RT_EACCES, ERR_RT_EADDRINUSE,
  ERR_RT_INVALID_JSON, ERR_RT_TIMEOUT,
  ERR_TS1361, ERR_TS2740, ERR_TS2741, ERR_TS2745, ERR_TS2820,
  ERR_TS6133, ERR_TS6133_IMPORT, ERR_TS7016, ERR_TS7053, ERR_TS2322_NULLABLE,
  errorRecoveryNodes,
} from './error-recovery';

// ── Architecture Nodes (35 nodes) ──────────────────────────────
export {
  ARCH_PLUGIN_LIFECYCLE, ARCH_HOOK_CHAINING, ARCH_XSTATE_MACHINE,
  ARCH_BRAIN_COORDINATION, ARCH_COMMAND_PATTERN, ARCH_EVENT_DRIVEN,
  ARCH_LAYERED, ARCH_DEPENDENCY_INJECTION,
  ARCH_CIRCUIT_BREAKER, ARCH_BULKHEAD, ARCH_SAGA, ARCH_CQRS,
  ARCH_EVENT_SOURCING, ARCH_MICROKERNEL, ARCH_PIPELINE,
  ARCH_MESSAGE_BROKER, ARCH_REVERSE_PROXY, ARCH_SIDECAR,
  ARCH_SHARED_LIBRARY, ARCH_MODULE_FEDERATION, ARCH_PLUGIN_REGISTRY,
  ARCH_MIDDLEWARE_CHAIN,
  ARCH_REPOSITORY, ARCH_UNIT_OF_WORK,
  ARCH_FACTORY, ARCH_STRATEGY, ARCH_OBSERVER,
  ARCH_DECORATOR, ARCH_ADAPTER, ARCH_FACADE,
  ARCH_COMPOSITE, ARCH_ITERATOR, ARCH_SINGLETON,
  ARCH_BUILDER, ARCH_NULL_OBJECT,
  architectureNodes,
} from './architecture-nodes';

// ── NLP Component Nodes (15 nodes) ─────────────────────────────
export {
  NLP_TOKENISER, NLP_DEPENDENCY_PARSE, NLP_SVO_EXTRACTION,
  NLP_VERB_FRAME_MATCH, NLP_INTENT_FSM,
  NLP_NER, NLP_SENTIMENT, NLP_TEMPORAL, NLP_COREFERENCE,
  NLP_INTENT_CLASSIFICATION,
  NLP_CLAIM_EXTRACTION, NLP_COMMITMENT_EXTRACTION,
  NLP_QUESTION_DETECTION, NLP_NEGATION_DETECTION,
  NLP_DETERMINISTIC_GUARANTEE,
  nlpComponentNodes,
} from './nlp-component-nodes';

// ── Build Order Nodes (10 nodes) ────────────────────────────────
export {
  BO01_TYPES_FIRST, BO02_ERROR_HANDLING_FIRST, BO03_RESOURCES_FIRST,
  BO04_EMPTY_STATE_FIRST, BO05_NEGATIVE_PATH_FIRST, BO06_BOUNDARY_VALIDATION,
  BO07_CONFIG_BEFORE_CODE, BO08_CONTRACT_BEFORE_IMPL, BO09_TEST_SHAPING,
  BO10_DEPLOYMENT_LAST,
  buildOrderNodes,
} from './build-order-nodes';

// ── Enforcement Nodes (15 nodes) ───────────────────────────────
export {
  ENF_ESCALATION_CUMULATIVE, ENF_ESCALATION_DECAY,
  ENF_ESCALATION_FIRST_SEVERITY, ENF_ESCALATION_REPEAT,
  ENF_PROFILE_TRUSTED, ENF_PROFILE_STANDARD, ENF_PROFILE_GUIDED,
  ENF_ADAPTIVE_SUCCESS_DROP, ENF_ADAPTIVE_VIOLATION_DROP,
  ENF_ADAPTIVE_SPEED_SLOW, ENF_ADAPTIVE_SPEED_FAST,
  ENF_ADAPTIVE_FOLLOWING,
  ENF_SAFETY_GATE_OVERRIDE,
  ENF_SAMPLING_TRUSTED, ENF_RANDOM_SPOTCHECK,
  enforcementNodes,
} from './enforcement-nodes';

// ── Docker Container Nodes (35 nodes) ──────────────────────────
export {
  DOCKER_MULTI_STAGE_BUILD, DOCKER_DMINIMAL_BASE, DOCKER_LAYER_CACHING,
  DOCKER_BUILD_CONTEXT, DOCKER_IMAGE_LABELING, DOCKER_IMAGE_SCANNING,
  DOCKER_IMAGE_VERSIONING, DOCKER_DISTROLESS,
  DOCKER_NON_ROOT_USER, DOCKER_NO_SECRETS, DOCKER_READONLY_ROOTFS,
  DOCKER_CAPABILITY_DROP, DOCKER_NO_PRIVILEGED, DOCKER_RESOURCE_LIMITS,
  DOCKER_HEALTHCHECK,
  DOCKER_ENTRYPOINT, DOCKER_SIGNAL_HANDLING, DOCKER_GRACEFUL_SHUTDOWN,
  DOCKER_ENV_VARS, DOCKER_WORKING_DIR, DOCKER_TEMP_FILES, DOCKER_LOGGING,
  DOCKER_BUILDKIT, DOCKER_CACHE_MOUNTS, DOCKER_SQUASH,
  DOCKER_PLATFORM_BUILD, DOCKER_BUILD_ARGS, DOCKER_BUILD_SECRETS,
  DOCKER_DOCKERIGNORE,
  DOCKER_COMPOSE_HEALTHCHECK, DOCKER_NETWORK_ISOLATION, DOCKER_VOLUME_PERSISTENCE,
  DOCKER_RESTART_POLICY, DOCKER_DEPENDENCY_ORDER, DOCKER_RESOURCE_QUOTAS,
  dockerContainerNodes,
} from './docker-container-nodes';

// ── Data Validation Nodes (35 nodes) ──────────────────────────
export {
  VALID_SCHEMA_FIRST,
  VALID_RUNTIME_GUARD_INPUT, VALID_RUNTIME_GUARD_OUTPUT, VALID_RUNTIME_GUARD_BOUNDARY,
  VALID_RUNTIME_GUARD_CONFIG, VALID_RUNTIME_GUARD_ENV, VALID_RUNTIME_GUARD_UNKNOWN, VALID_RUNTIME_GUARD_JSON,
  VALID_TYPES_EXACT, VALID_TYPES_BRANDED, VALID_TYPES_NOMINAL, VALID_TYPES_TEMPLATE_LITERAL,
  VALID_TYPES_DISCRIMINATED_UNION, VALID_TYPES_RESULT, VALID_TYPES_OPTIONAL,
  VALID_ASYNC_PARSE, VALID_ASYNC_FETCH, VALID_ASYNC_DB, VALID_ASYNC_TIMEOUT, VALID_ASYNC_RETRY,
  VALID_COMPLEX_NESTED, VALID_COMPLEX_ARRAY, VALID_COMPLEX_MAP, VALID_COMPLEX_UNION, VALID_COMPLEX_INTERSECTION,
  VALID_SECURITY_SQL_INJECTION, VALID_SECURITY_XSS, VALID_SECURITY_COMMAND_INJECTION,
  VALID_SECURITY_PATH_TRAVERSAL, VALID_SECURITY_PROTOTYPE_POLLUTION,
  VALID_IMMUTABLE_FREEZE, VALID_NUMERIC_RANGE, VALID_REDACT_SECRETS,
  VALID_CIRCULAR_REF, VALID_COERCION_EXPLICIT,
  dataValidationNodes,
} from './data-validation-nodes';

// ── LLM Agent Runtime Nodes (40 nodes) ─────────────────────────
export {
  LLMRT_CONTEXT_WINDOW_MGMT, LLMRT_CONTEXT_COMPACTION, LLMRT_CONTEXT_PRIORITY,
  LLMRT_CONTEXT_EVICTION, LLMRT_CONTEXT_CACHE, LLMRT_CONTEXT_SUMMARIZATION,
  LLMRT_CONTEXT_ANCHORING, LLMRT_CONTEXT_INJECTION,
  LLMRT_PROMPT_INJECTION_DEFENSE, LLMRT_OUTPUT_FILTERING, LLMRT_CONTENT_MODERATION,
  LLMRT_RATE_LIMITING, LLMRT_TOKEN_BUDGET, LLMRT_COST_CONTROL,
  LLMRT_TOOL_SELECTION, LLMRT_TOOL_PARAMETER_VALIDATION, LLMRT_TOOL_ERROR_HANDLING,
  LLMRT_TOOL_CHAINING, LLMRT_TOOL_PARALLEL, LLMRT_TOOL_RETRY,
  LLMRT_CHAIN_OF_THOUGHT, LLMRT_PLANNING_BEFORE_ACTION, LLMRT_SELF_CORRECTION,
  LLMRT_UNCERTAINTY_DETECTION, LLMRT_CONFIDENCE_CALIBRATION, LLMRT_ERROR_DETECTION,
  LLMRT_MULTI_AGENT_COORDINATION, LLMRT_HUMAN_IN_THE_LOOP, LLMRT_FEEDBACK_LOOP,
  LLMRT_MEMORY_MANAGEMENT, LLMRT_STATE_PERSISTENCE, LLMRT_COMPACTION_SURVIVAL,
  LLMRT_ADVERSARIAL_ROBUSTNESS, LLMRT_DISTRIBUTION_SHIFT, LLMRT_HALLUCINATION_PREVENTION,
  LLMRT_FACTUAL_CONSISTENCY, LLMRT_TEMPORAL_CONSISTENCY, LLMRT_CROSS_MODAL_ALIGNMENT,
  LLMRT_EMERGENT_BEHAVIOR, LLMRT_SAFETY_ALIGNMENT,
  llmAgentRuntimeNodes,
} from './llm-agent-runtime-nodes';

// ── Domain-Specific Nodes (130 nodes) ───────────────────────────
export {
  DOMAIN_CLI_ARG_PARSING, DOMAIN_CLI_SUBCOMMANDS, DOMAIN_CLI_FLAGS_OPTIONS,
  DOMAIN_CLI_HELP_TEXT, DOMAIN_CLI_EXIT_CODES, DOMAIN_CLI_STDIN_HANDLING,
  DOMAIN_CLI_STDOUT_FORMATTING, DOMAIN_CLI_STDERR_ERRORS, DOMAIN_CLI_CONFIG_FILE,
  DOMAIN_CLI_ENV_VARS, DOMAIN_CLI_SIGNAL_HANDLING, DOMAIN_CLI_PROGRESS_BAR,
  DOMAIN_CLI_COLOR_OUTPUT, DOMAIN_CLI_INTERACTIVE_PROMPT, DOMAIN_CLI_COMPLETION,
  DOMAIN_BUILD_ENTRY_POINT, DOMAIN_BUILD_OUTPUT_STRUCTURE, DOMAIN_BUILD_DEPENDENCY_RESOLUTION,
  DOMAIN_BUILD_TREE_SHAKING, DOMAIN_BUILD_SOURCEMAPS, DOMAIN_BUILD_MODULE_FORMAT,
  DOMAIN_BUILD_TARGET_PLATFORM, DOMAIN_BUILD_EXTERNAL_DEPS, DOMAIN_BUILD_MINIFICATION,
  DOMAIN_BUILD_ASSETS, DOMAIN_BUILD_WATCH_MODE, DOMAIN_BUILD_INCREMENTAL,
  DOMAIN_BUILD_PLUGIN_SYSTEM, DOMAIN_BUILD_CUSTOM_LOADERS, DOMAIN_BUILD_ENV_INJECTION,
  DOMAIN_API_REST_DESIGN, DOMAIN_API_GRAPHQL_SCHEMA, DOMAIN_API_AUTHENTICATION,
  DOMAIN_API_AUTHORIZATION, DOMAIN_API_RATE_LIMITING, DOMAIN_API_VERSIONING,
  DOMAIN_API_PAGINATION, DOMAIN_API_ERROR_RESPONSES, DOMAIN_API_CORS,
  DOMAIN_API_INPUT_VALIDATION, DOMAIN_API_OUTPUT_SERIALIZATION, DOMAIN_API_CACHING,
  DOMAIN_API_WEBHOOKS, DOMAIN_API_OPENAPI_SPEC, DOMAIN_API_MIDDLEWARE_STACK,
  DOMAIN_ORCH_TASK_QUEUE, DOMAIN_ORCH_WORKER_POOL, DOMAIN_ORCH_SCHEDULER,
  DOMAIN_ORCH_STATE_MACHINE, DOMAIN_ORCH_EVENT_LOOP, DOMAIN_ORCH_MESSAGE_QUEUE,
  DOMAIN_ORCH_DISTRIBUTED_LOCK, DOMAIN_ORCH_IDEMPOTENCY, DOMAIN_ORCH_COMPENSATING_ACTION,
  DOMAIN_ORCH_SAGA_COORDINATOR, DOMAIN_ORCH_CIRCUIT_BREAKER, DOMAIN_ORCH_RETRY_POLICY,
  DOMAIN_ORCH_TIMEOUT_HANDLING, DOMAIN_ORCH_DEAD_LETTER, DOMAIN_ORCH_OBSERVABILITY,
  DOMAIN_ORCH_WORKFLOW_ENGINE, DOMAIN_ORCH_DAG_SCHEDULER, DOMAIN_ORCH_CRON_SCHEDULER,
  DOMAIN_ORCH_EVENT_SOURCING_CQRS, DOMAIN_ORCH_OBSERVABILITY_TRACE,
  DOMAIN_CLI_SHELL_COMPLETION, DOMAIN_CLI_MAN_PAGES, DOMAIN_CLI_PIPING,
  DOMAIN_CLI_BACKGROUND_JOBS, DOMAIN_CLI_SIGNALS_ADVANCED, DOMAIN_CLI_COLOR_THEMES,
  DOMAIN_CLI_OUTPUT_FORMAT, DOMAIN_CLI_DRY_RUN, DOMAIN_CLI_VERBOSE_LOGGING, DOMAIN_CLI_DEBUG_MODE,
  DOMAIN_API_WEBSOCKET, DOMAIN_API_SSE, DOMAIN_API_GRPC,
  DOMAIN_API_WEBHOOK_SECURITY, DOMAIN_API_API_KEY_MGMT, DOMAIN_API_OAUTH_FLOW,
  DOMAIN_API_JWT_HANDLING, DOMAIN_API_CORS_ADVANCED, DOMAIN_API_FILE_UPLOAD,
  DOMAIN_API_STREAMING_RESPONSE,
  DOMAIN_ORCH_CONSENSUS, DOMAIN_ORCH_LEADER_ELECTION, DOMAIN_ORCH_DISTRIBUTED_TRACING,
  DOMAIN_ORCH_METRICS_COLLECTION, DOMAIN_ORCH_LOG_AGGREGATION, DOMAIN_ORCH_HEALTH_CHECK,
  DOMAIN_ORCH_AUTO_SCALING, DOMAIN_ORCH_CONFIG_MGMT, DOMAIN_ORCH_SERVICE_DISCOVERY,
  DOMAIN_ORCH_CIRCUIT_RESET,
  domainSpecificNodes,
} from './domain-specific-nodes';

// ── CI/CD Pipeline Nodes (35 nodes) ────────────────────────────
export {
  CICD_PIPELINE_STAGES, CICD_BUILD_AUTOMATION, CICD_TEST_AUTOMATION,
  CICD_LINT_AUTOMATION, CICD_SECURITY_SCAN, CICD_ARTIFACT_MANAGEMENT,
  CICD_CACHE_STRATEGY, CICD_PARALLEL_JOBS,
  CICD_BLUE_GREEN, CICD_CANARY, CICD_ROLLING,
  CICD_RECREATE, CICD_SHIFTING, CICD_ROLLBACK, CICD_DEPLOYMENT_GATE,
  CICD_SECRET_MANAGEMENT, CICD_SIGNING, CICD_SBOM,
  CICD_IMAGE_SCAN, CICD_COMPLIANCE_CHECK, CICD_ACCESS_CONTROL,
  CICD_CODE_COVERAGE, CICD_MUTATION_TESTING, CICD_COMPLEXITY_CHECK,
  CICD_DEPENDENCY_CHECK, CICD_LICENSE_CHECK, CICD_STATIC_ANALYSIS,
  CICD_SEMANTIC_VERSIONING, CICD_CHANGELOG, CICD_RELEASE_NOTES,
  CICD_RELEASE_APPROVAL,
  CICD_INFRASTRUCTURE_AS_CODE, CICD_TERRAFORM, CICD_KUSTOMIZE, CICD_HELM,
  ciCdPipelineNodes,
} from './ci-cd-pipeline-nodes';

// ── Async Concurrency Nodes (30 nodes) ─────────────────────────
export {
  ASYNC_EVENT_LOOP, ASYNC_MICROTASK, ASYNC_MACROTASK,
  ASYNC_STACK_TRACE, ASYNC_ERROR_PROPAGATION, ASYNC_PROMISE_CHAIN,
  ASYNC_MUTEX, ASYNC_SEMAPHORE, ASYNC_RW_LOCK,
  ASYNC_BARRIER, ASYNC_LATCH, ASYNC_CONDITION_VARIABLE,
  ASYNC_RESOURCE_POOL, ASYNC_CONNECTION_POOL, ASYNC_THREAD_POOL,
  ASYNC_TASK_QUEUE, ASYNC_RATE_LIMITER, ASYNC_CIRCUIT_BREAKER,
  ASYNC_PUB_SUB, ASYNC_PRODUCER_CONSUMER, ASYNC_READERS_WRITERS,
  ASYNC_WAIT_NOTIFY, ASYNC_COOPERATIVE_CANCELLATION, ASYNC_BACKPRESSURE,
  ASYNC_DEADLOCK_PREVENTION, ASYNC_LIVELOCK_DETECTION, ASYNC_STARVATION_PREVENTION,
  ASYNC_PRIORITY_INVERSION, ASYNC_THUNDERING_HERD, ASYNC_SHARDING,
  asyncConcurrencyNodes,
} from './async-concurrency-nodes';

// ── Combined Array ─────────────────────────────────────────────

import { principles } from './principles';
import { ironLaws } from './iron-laws';
import { gateRequirements } from './gate-requirements';
import { antiPatterns } from './anti-patterns';
import { analysisOrders } from './analysis-orders';
import { failurePatterns } from './failure-patterns';
import { fixPatterns } from './fix-patterns';
import { testingNodes } from './testing-nodes';
import { securityNodes } from './security-nodes';
import { typescriptNodes } from './typescript-nodes';
import { concurrencyNodes } from './concurrency-nodes';
import { persistenceNodes } from './persistence-nodes';
import { gateKnowledge } from './gate-knowledge';
import { errorRecoveryNodes } from './error-recovery';
import { architectureNodes } from './architecture-nodes';
import { nlpComponentNodes } from './nlp-component-nodes';
import { buildOrderNodes } from './build-order-nodes';
import { enforcementNodes } from './enforcement-nodes';
import { dockerContainerNodes } from './docker-container-nodes';
import { dataValidationNodes } from './data-validation-nodes';
import { llmAgentRuntimeNodes } from './llm-agent-runtime-nodes';
import { domainSpecificNodes } from './domain-specific-nodes';
import { ciCdPipelineNodes } from './ci-cd-pipeline-nodes';
import { asyncConcurrencyNodes } from './async-concurrency-nodes';

/**
 * ALL_KNOWLEDGE_NODES — the complete knowledge graph.
 *
 * This array contains every node in the EIE knowledge graph.
 * The context matcher traverses this to find relevant nodes.
 * The bullet generator uses matched nodes for guidance.
 * The warhead generator uses matched nodes for re-alignment.
 */
export const ALL_KNOWLEDGE_NODES: KnowledgeNode[] = [
  ...principles,            // 50
  ...ironLaws,              // 22
  ...gateRequirements,      // 36
  ...antiPatterns,          // 80
  ...analysisOrders,        // 6
  ...failurePatterns,       // 20
  ...fixPatterns,           // 80
  ...testingNodes,          // 35
  ...securityNodes,         // 36
  ...typescriptNodes,       // 44
  ...concurrencyNodes,      // 30
  ...persistenceNodes,      // 15
  ...gateKnowledge,         // 36
  ...errorRecoveryNodes,    // 50
  ...architectureNodes,     // 35
  ...nlpComponentNodes,     // 15
  ...buildOrderNodes,       // 10
  ...enforcementNodes,      // 15
  ...dockerContainerNodes,  // 35
  ...dataValidationNodes,   // 35
  ...llmAgentRuntimeNodes,  // 40
  ...domainSpecificNodes,   // 130
  ...ciCdPipelineNodes,     // 35
  ...asyncConcurrencyNodes, // 30
];

/**
 * Get a node by ID.
 */
export function getNodeById(id: string): KnowledgeNode | undefined {
  return ALL_KNOWLEDGE_NODES.find(n => n.id === id);
}

/**
 * Get nodes by category.
 */
export function getNodesByCategory(category: KnowledgeNode['category']): KnowledgeNode[] {
  return ALL_KNOWLEDGE_NODES.filter(n => n.category === category);
}

/**
 * Get the total node count.
 */
export function getNodeCount(): number {
  return ALL_KNOWLEDGE_NODES.length;
}
