/**
 * src/eie/nodes/iron-laws.ts — 22 Iron Laws
 *
 * 10 from Runtime Grade Bible (RGB) Appendix F + 12 from T3 §1.
 * Iron Laws are non-negotiable. They are the foundation of all
 * runtime-grade engineering. Every other rule derives from these.
 *
 * Source: RUNTIME_GRADE_BIBLE.md + T3_ALGORITHMIC_SYSTEMS.md
 */

import type { KnowledgeNode } from '../types';

// ══ RGB IRON LAWS (IL01-IL10) ════════════════════════════════

export const IL01_OUTPUT_IS_REALITY: KnowledgeNode = {
  id: 'IL01-OUTPUT-IS-REALITY',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL01',
  rule: [
    'OUTPUT IS REALITY: The only truth is what the filesystem contains after execution.',
    'Agent claims about what it "did" are irrelevant. The filesystem either changed or it did not.',
    'A function that returns a positive flag but wrote nothing to disk has produced nothing.',
    'Verification MUST compare the filesystem state before and after execution.',
    'Never trust agent prose. Never trust return values alone. Always verify the filesystem diff.',
    'The Merkle tree snapshot is the single source of truth for what actually happened.',
    'This is the first iron law because all other laws fail without it.',
  ].join('\n'),
  detectionMethod: 'Claim-reality verification: compare agent claims against filesystem diff, test results, and RGE scores. If the agent claims work was done but the filesystem shows no change, flag.',
  fixTemplate: 'After any operation, verify the filesystem changed: take a Merkle snapshot before, execute, take a snapshot after. If no diff, the work was not done.',
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'TEST', 'AUDIT', 'DELIVERY'] },
    { field: 'phase', op: 'equals', value: 'post-execution' },
  ],
  bulletTemplate: 'Claim without filesystem change. Verify: Merkle diff must show the work.',
  warheadTemplate: [
    '# IL01 Violation: Output Is Not Reality',
    '',
    '## What Happened',
    'The agent claimed to have performed work, but the filesystem shows no change.',
    '',
    '## Why This Is Critical',
    'Without filesystem verification, the agent can claim anything. This is the foundation',
    'of all runtime-grade engineering. Every other law depends on this one.',
    '',
    '## How to Fix',
    '1. Take a Merkle snapshot before the operation.',
    '2. Execute the operation.',
    '3. Take a Merkle snapshot after.',
    '4. If no diff, the work was not done — redo it.',
    '',
    '## Reference',
    'IL01 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'claim-reality', verify: 'claim-reality', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['P11-OUTPUT-IS-THE-WORK', 'IL11-OUTPUT-IS-PROOF', 'R22-CLAIM-REALITY'],
  selfVerified: true,
};

export const IL02_CONTRACT_HONORED: KnowledgeNode = {
  id: 'IL02-CONTRACT-HONORED',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL02',
  rule: [
    'CONTRACT HONORED: Every function must honor its declared contract across ALL paths.',
    'If a function declares return type T, every code path must return T — including catch blocks.',
    'If a function accepts type U, it must validate that input is actually U before using it.',
    'A catch block that returns null for a non-nullable return type is a contract violation.',
    'The type system is a promise. The runtime must keep it.',
    'Contracts are not "best effort" — they are binary. Either you honor them or you don\'t.',
    'This is the second iron law because it is the boundary between type-safe and type-unsafe code.',
  ].join('\n'),
  detectionMethod: 'AST + TypeChecker: Find function declarations with explicit return types. Verify all catch blocks within return the correct type or throw. Check that input parameters are validated at boundaries.',
  fixTemplate: 'Every catch must either throw (propagating the error) or return a value of the declared type. Never return null/undefined for non-nullable. Use unknown at boundaries and narrow.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
    { field: 'fileType', op: 'equals', value: 'ts' },
  ],
  bulletTemplate: 'Contract violation: catch returns wrong type for {func}. Throw or return valid {type}.',
  warheadTemplate: [
    '# IL02 Violation: Contract Not Honored',
    '',
    '## What Happened',
    'A function does not honor its declared contract across all code paths.',
    '',
    '## How to Fix',
    'Ensure every path returns the declared type. In catch blocks, either throw or return',
    'a valid fallback of the correct type.',
    '',
    '## Reference',
    'IL02 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 1,
  links: ['P10-OUTPUT-CONTRACT', 'P2-TYPE-CERTAINTY'],
  selfVerified: true,
};

export const IL03_ASYNC_COMPLETENESS: KnowledgeNode = {
  id: 'IL03-ASYNC-COMPLETENESS',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL03',
  rule: [
    'ASYNC COMPLETENESS: Every async operation must complete in all scenarios — positive or negative.',
    'Every Promise must have error handling (.catch or try/await/catch).',
    'Every async function must handle its own rejections.',
    'Fire-and-forget async is a defect unless explicitly designed with a background error handler.',
    'Loading flags must be reset in finally blocks, not just on the happy path.',
    'Resources acquired in async context must be cleaned up in finally blocks.',
    'Async code that "usually works" is async code that will crash in production.',
  ].join('\n'),
  detectionMethod: 'CFG: Find .then() chains without .catch(). Find async functions called without await and without .catch(). Find loading flags set before await without finally reset.',
  fixTemplate: 'Every async call needs: await + try/catch, or .catch(). Loading flags need finally blocks. Resources need finally cleanup.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
    { field: 'fileType', op: 'equals', value: 'ts' },
  ],
  bulletTemplate: 'Async operation without error handling at line {line}. Add try/catch or .catch().',
  warheadTemplate: [
    '# IL03 Violation: Async Incompleteness',
    '',
    '## What Happened',
    'An async operation lacks error handling for negative scenarios.',
    '',
    '## How to Fix',
    'Wrap every await in try/catch. Add .catch() to every .then(). Reset loading flags',
    'in finally. Clean up resources in finally.',
    '',
    '## Reference',
    'IL03 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 4,
  links: ['P9-ASYNC-DISCIPLINE', 'P4-RESOURCE-LIFECYCLE', 'P5-ATOMIC-STATE'],
  selfVerified: true,
};

export const IL04_NO_SILENT_FAILURE: KnowledgeNode = {
  id: 'IL04-NO-SILENT-FAILURE',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL04',
  rule: [
    'NO SILENT FAILURE: Every error must be handled, logged, and either recovered or propagated.',
    'An empty catch block is always a defect. A catch that only logs without recovery is swallowing.',
    'A catch that returns null/undefined for a non-nullable type is a silent failure.',
    'If an operation fails, the failure must be visible — either in logs, in the return value, or as a thrown error.',
    'Silent failures cause downstream code to operate on invalid data, producing cascading corruption.',
    'The cost of a visible error is 1 debug cycle. The cost of a silent error is 100 debug cycles.',
    'Zero-tolerance for silent failure. If you catch, you MUST handle.',
  ].join('\n'),
  detectionMethod: 'AST: Find empty catch blocks, comment-only catches, log-only-without-rethrow catches. Check that every catch has meaningful handling.',
  fixTemplate: 'Every catch must: (1) log with context, (2) recover with a fallback OR re-throw with context. No exceptions.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Silent failure at line {line}: catch swallows error. Add: log + recover or re-throw.',
  warheadTemplate: [
    '# IL04 Violation: Silent Failure',
    '',
    '## What Happened',
    'An error is caught and silently discarded — not logged, not recovered, not propagated.',
    '',
    '## How to Fix',
    'Every catch must do something meaningful: log with context, return a fallback, or re-throw.',
    '',
    '## Reference',
    'IL04 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'sre-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 1,
  links: ['P3-ERROR-COMPLETENESS', 'P10-OUTPUT-CONTRACT'],
  selfVerified: true,
};

export const IL05_ATOMIC_TRANSITION: KnowledgeNode = {
  id: 'IL05-ATOMIC-TRANSITION',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL05',
  rule: [
    'ATOMIC TRANSITION: State transitions must be atomic — no torn states.',
    'Related state changes must happen together in a single assignment or within a try/finally block.',
    'If an async operation occurs between two state mutations, a try/finally is mandatory.',
    'A torn state is one where some properties have been updated but others haven\'t — the object is inconsistent.',
    'Torn states cause bugs that are extremely hard to reproduce because they depend on timing.',
    'Use the spread pattern ({ ...prev, ...updates }) for atomic multi-property updates.',
    'For sequential mutations with awaits, always wrap in try/finally to ensure rollback.',
  ].join('\n'),
  detectionMethod: 'CFG: Detect sequential property mutations interleaved with awaits without try/finally. Detect loading flags set before await without finally reset.',
  fixTemplate: 'Use atomic spread: state = { ...prev, loading: false, data, error: null }. Or use try/finally for sequential mutations with awaits.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Torn state risk: mutations across await boundary without try/finally.',
  warheadTemplate: [
    '# IL05 Violation: Non-Atomic State Transition',
    '',
    '## What Happened',
    'State is mutated in separate statements across an async boundary without try/finally.',
    '',
    '## How to Fix',
    'Use atomic spread assignment or wrap in try/finally.',
    '',
    '## Reference',
    'IL05 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 4,
  links: ['P5-ATOMIC-STATE', 'P3-ERROR-COMPLETENESS'],
  selfVerified: true,
};

export const IL06_RESOURCE_OWNERSHIP: KnowledgeNode = {
  id: 'IL06-RESOURCE-OWNERSHIP',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL06',
  rule: [
    'RESOURCE OWNERSHIP: Whoever acquires a resource owns its lifecycle.',
    'If you call setInterval, you must call clearInterval — in a finally block.',
    'If you open a file handle, you must close it — in a finally block.',
    'If you add an event listener, you must remove it — in a finally block.',
    'There is no "the caller will clean up." That is a leak.',
    'The cleanup must be in the same function scope as the acquisition, in a finally block.',
    'Resources leaked in a long-running process accumulate until the process dies.',
  ].join('\n'),
  detectionMethod: 'CFG: Trace resource acquisitions and verify cleanup exists in a finally block in the same scope.',
  fixTemplate: 'Wrap all resource usage in try/finally: acquire in try, clean up in finally.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
    { field: 'codePattern', op: 'matches', value: 'setInterval|setTimeout|openSync|createReadStream|addEventListener' },
  ],
  bulletTemplate: 'Resource {name} acquired without finally cleanup at line {line}.',
  warheadTemplate: [
    '# IL06 Violation: Resource Leak',
    '',
    '## What Happened',
    'A resource was acquired but its cleanup is missing from the finally block.',
    '',
    '## How to Fix',
    'Wrap in try/finally. The finally block must contain the cleanup call.',
    '',
    '## Reference',
    'IL06 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 4,
  links: ['P4-RESOURCE-LIFECYCLE', 'P9-ASYNC-DISCIPLINE'],
  selfVerified: true,
};

export const IL07_ENVIRONMENT_INDEPENDENCE: KnowledgeNode = {
  id: 'IL07-ENVIRONMENT-INDEPENDENCE',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL07',
  rule: [
    'ENVIRONMENT INDEPENDENCE: Code must work identically across all environments.',
    'No hardcoded paths — use path.join, os.homedir, __dirname, process.cwd.',
    'No environment-specific values in source code — use config files and env vars.',
    'No machine-specific assumptions (OS, architecture, user, directory structure).',
    'Code tested on the developer\'s machine must produce the same result in the container.',
    'The container is a different machine with a different user and different paths.',
    'Hardcoded paths are the #1 cause of "works on my machine" bugs.',
  ].join('\n'),
  detectionMethod: 'Regex: Scan for hardcoded path patterns (/home/, /Users/, C:\\, /var/www/) outside path.join/path.resolve.',
  fixTemplate: 'Replace all hardcoded paths with dynamic resolution: path.join(__dirname, ...), os.homedir(), process.cwd().',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Hardcoded path at line {line}. Replace with path.join(__dirname, ...).',
  warheadTemplate: [
    '# IL07 Violation: Environment Dependency',
    '',
    '## What Happened',
    'Source code contains hardcoded paths that only work on one machine.',
    '',
    '## How to Fix',
    'Use path.join(__dirname, ...), os.homedir(), or process.cwd() for all paths.',
    '',
    '## Reference',
    'IL07 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 2,
  links: ['P7-PATH-RESOLUTION', 'P8-CONFIG-VALIDATION'],
  selfVerified: true,
};

export const IL08_FAIL_FAST_CONFIG: KnowledgeNode = {
  id: 'IL08-FAIL-FAST-CONFIG',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL08',
  rule: [
    'FAIL FAST CONFIG: Invalid configuration must crash at startup, not at runtime.',
    'Validate every config value at load time — type, range, and presence.',
    'process.env values are always strings or undefined — parse and validate before use.',
    'If a required config value is missing, throw immediately with a clear message.',
    'If a config value is out of range, throw immediately with the expected range.',
    'Never let invalid config propagate deep into the system — it causes failures far from the cause.',
    'A startup crash is debuggable. A runtime crash 3 hours later is not.',
  ].join('\n'),
  detectionMethod: 'AST: Find process.env and config.* accesses without nearby validation.',
  fixTemplate: 'Create a config loader that validates every value at startup. Throw on invalid/missing values.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Unvalidated config value {name}. Add: type + range + presence check.',
  warheadTemplate: [
    '# IL08 Violation: No Fail-Fast Config',
    '',
    '## What Happened',
    'Configuration values are used without validation, causing failures deep in the system.',
    '',
    '## How to Fix',
    'Validate all config at startup. Parse env vars. Check types and ranges. Throw on invalid.',
    '',
    '## Reference',
    'IL08 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'block',
  layer: 2,
  links: ['P8-CONFIG-VALIDATION', 'P7-PATH-RESOLUTION'],
  selfVerified: true,
};

export const IL09_WIRE_DONT_DECLARE: KnowledgeNode = {
  id: 'IL09-WIRE-DONT-DECLARE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL09',
  rule: [
    'WIRE, DON\'T DECLARE: Code that calls functions at runtime is worth more than code that declares interfaces.',
    'A declared function that is never wired (called) is dead code.',
    'An interface with no implementation is documentation, not software.',
    'Import a module and CALL it. Don\'t just import it and assume it works.',
    'After importing, verify the export exists (P1), then call it.',
    'Declarations are cheap. Wiring is the work. Only wired code is real.',
    'The build system must catch unwired declarations — dead exports are defects.',
  ].join('\n'),
  detectionMethod: 'AST: Find exported functions/classes that are never imported or called. Find imported symbols that are never used. Dead code detection.',
  fixTemplate: 'Wire every declaration: import the function, verify it exists, call it. Remove dead exports. If a function is exported but never called, either call it or delete it.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Dead export {name}: function declared but never called. Wire it or remove it.',
  warheadTemplate: [
    '# IL09 Violation: Declared But Not Wired',
    '',
    '## What Happened',
    'A function/interface is declared but never actually called at runtime.',
    '',
    '## How to Fix',
    'Wire the function: import it, verify the export, call it. If it\'s dead, delete it.',
    '',
    '## Reference',
    'IL09 — Wire, Don\'t Declare — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'no-dead-code', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'warn',
  layer: 2,
  links: ['P1-DEFENSIVE-IMPORT', 'P6-DEPENDENCY-CHECK', 'R14-CFG-DEAD-CODE'],
  selfVerified: true,
};

export const IL10_EVIDENCE_IS_MECHANICAL: KnowledgeNode = {
  id: 'IL10-EVIDENCE-IS-MECHANICAL',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL10',
  rule: [
    'EVIDENCE IS MECHANICAL: Evidence must be produced by mechanical execution, not by agent claims.',
    'TypeScript compilation evidence = tsc exit code 0, not "I checked the types."',
    'Test evidence = test runner exit code 0 with pass count, not "tests pass."',
    'Build evidence = bun build exit code 0 with bundle file, not "it builds."',
    'File evidence = fs.existsSync returning true with file size, not "the file is there."',
    'Mechanical evidence is reproducible. Agent claims are not.',
    'Every evidence requirement must map to a specific mechanical check.',
  ].join('\n'),
  detectionMethod: 'Check that evidence IDs map to mechanical execution methods (exec-tsc, exec-build, test-run, fs-check). Flag evidence that is only an agent claim.',
  fixTemplate: 'Map every evidence requirement to a mechanical check. Execute the check. Store the result. The result is the evidence — not the agent\'s prose.',
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'TEST', 'AUDIT', 'DELIVERY'] },
  ],
  bulletTemplate: 'Evidence {id} is a claim, not mechanical. Execute the check and store the result.',
  warheadTemplate: [
    '# IL10 Violation: Evidence Is Not Mechanical',
    '',
    '## What Happened',
    'Evidence is claimed by the agent but not verified by mechanical execution.',
    '',
    '## How to Fix',
    'Execute the mechanical check (tsc, bun build, test runner, fs.existsSync).',
    'Store the result. The mechanical result IS the evidence.',
    '',
    '## Reference',
    'IL10 — Runtime Grade Bible Appendix F',
  ].join('\n'),
  evidenceSpec: { id: 'evidence-mechanical', verify: 'claim-reality', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'R22-CLAIM-REALITY'],
  selfVerified: true,
};

// ══ T3 IRON LAWS (IL11-IL22) ════════════════════════════════

export const IL11_OUTPUT_IS_PROOF: KnowledgeNode = {
  id: 'IL11-OUTPUT-IS-PROOF',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL11',
  rule: [
    'OUTPUT IS PROOF: The only proof of work is observable output.',
    'If you wrote code, the build must produce a bundle. If you added a test, the test runner must execute it.',
    'If you fixed a bug, the test that reproduced it must now pass.',
    'If you added a feature, the feature must be mechanically demonstrable.',
    'No proof = no work. Claiming work without proof is fraud.',
    'The agent\'s word about what it did is not proof. The filesystem and test results are proof.',
    'This extends IL01: not only must the filesystem change, the change must prove the claimed work.',
  ].join('\n'),
  detectionMethod: 'Compare agent claims against: (1) filesystem diff, (2) test results, (3) RGE scores. If claims don\'t match reality, flag.',
  fixTemplate: 'After every claimed action: (1) build the project, (2) run tests, (3) verify the filesystem diff shows the claimed change.',
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'TEST', 'AUDIT', 'DELIVERY'] },
  ],
  bulletTemplate: 'Claim without proof: {claim}. Build + test + diff must demonstrate it.',
  warheadTemplate: [
    '# IL11 Violation: No Proof of Work',
    '',
    '## What Happened',
    'The agent claims to have done work but cannot demonstrate it with output.',
    '',
    '## How to Fix',
    'Build. Test. Diff. If any of these don\'t show the claimed change, the work was not done.',
    '',
    '## Reference',
    'IL11 — Output Is Proof — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'claim-reality', verify: 'claim-reality', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'P11-OUTPUT-IS-THE-WORK'],
  selfVerified: true,
};

export const IL12_EMPTY_IS_NOT_SUCCESS: KnowledgeNode = {
  id: 'IL12-EMPTY-IS-NOT-SUCCESS',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL12',
  rule: [
    'EMPTY IS NOT SUCCESS: An empty result is not a positive result.',
    '[].every(fn) === true is vacuous — it means nothing was validated.',
    'An empty diff means nothing was changed — not that everything is correct.',
    'Zero test results means no tests ran — not that all tests pass.',
    'An empty collection is not proof of consensus, uniqueness, or validity.',
    'Guard every collection operation with explicit empty-state checks.',
    'An empty result must be reported as empty, not as success.',
  ].join('\n'),
  detectionMethod: 'AST: Find .every(), Set.size comparisons, .length checks on collections in validation/consensus contexts without empty guards.',
  fixTemplate: 'Before every collection operation: if (items.length === 0) return { valid: false, reason: "empty" }.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'AUDIT'] },
  ],
  bulletTemplate: 'Empty collection treated as valid at line {line}. Add: length === 0 guard.',
  warheadTemplate: [
    '# IL12 Violation: Empty Treated As Success',
    '',
    '## What Happened',
    'A collection operation on an empty input is treated as a positive result.',
    '',
    '## How to Fix',
    'Guard with explicit empty checks. Report empty as empty, not as success.',
    '',
    '## Reference',
    'IL12 — Empty Is Not Success — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'no-critical', verify: 'rge-audit', minQuality: 0.95 },
  severity: 'warn',
  layer: 2,
  links: ['P12-EMPTY-STATE-GUARD', 'P11-OUTPUT-IS-THE-WORK'],
  selfVerified: true,
};

export const IL13_RULE_OWNERSHIP_EXCLUSIVE: KnowledgeNode = {
  id: 'IL13-RULE-OWNERSHIP-EXCLUSIVE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL13',
  rule: [
    'RULE OWNERSHIP IS EXCLUSIVE: Every rule has exactly ONE owning engine.',
    'No two engines may enforce the same rule — this causes conflicting results and confusion.',
    'The rule ownership matrix (RULE_OWNERSHIP) is the single source of truth.',
    'If SF owns "no-empty-catch", RGE must not also check for it.',
    'Duplicate enforcement wastes computation and produces contradictory verdicts.',
    'When a rule spans concerns, assign primary ownership and reference from others.',
    'The T1_TO_OWNER map resolves which engine handles each T1 principle.',
  ].join('\n'),
  detectionMethod: 'Check RULE_OWNERSHIP matrix for duplicate entries. Verify no two engines detect the same rule.',
  fixTemplate: 'Consult RULE_OWNERSHIP. If a rule has multiple owners, assign to one and remove from others.',
  conditions: [
    { field: 'gate', op: 'equals', value: 'AUDIT' },
  ],
  bulletTemplate: 'Rule {id} has multiple owners. Assign to one engine per RULE_OWNERSHIP.',
  warheadTemplate: [
    '# IL13 Violation: Duplicate Rule Ownership',
    '',
    '## What Happened',
    'A rule is enforced by multiple engines, causing conflicting results.',
    '',
    '## How to Fix',
    'Assign to exactly one owner in RULE_OWNERSHIP. Remove from others.',
    '',
    '## Reference',
    'IL13 — Rule Ownership Is Exclusive — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'no-conflicts', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'warn',
  layer: 5,
  links: ['R01-HOOK-CONTRACT', 'AP-DUPLICATE-ENFORCEMENT'],
  selfVerified: true,
};

export const IL14_ANALYSIS_ORDER_MATTERS: KnowledgeNode = {
  id: 'IL14-ANALYSIS-ORDER-MATTERS',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL14',
  analysisOrder: 0,
  rule: [
    'ANALYSIS ORDER MATTERS: Lower-order analysis filters before higher-order runs.',
    'Order 0: Pass-through (no analysis).',
    'Order 1: Regex/candidate generation (warhead hooks) — fast, filters obvious violations.',
    'Order 2: AST walker (structural rules — SemanticFirewall) — catches structural defects.',
    'Order 3: TypeChecker queries (type safety — SemanticFirewall) — catches type violations.',
    'Order 4: CFG/DFA (resource lifecycle, floating promises) — catches control flow defects.',
    'Order 5: Execution verification (scope diff, evidence integrity) — catches runtime defects.',
    'Higher orders are more expensive but more accurate. Running them out of order wastes resources.',
  ].join('\n'),
  detectionMethod: 'Verify that analysis providers run in order 0→1→2→3→4→5. No higher-order analysis should run before lower-order completes.',
  fixTemplate: 'Use GATE_ANALYSIS_ROUTING to configure which orders run per gate. Always run lower orders first.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'TEST', 'AUDIT'] },
  ],
  bulletTemplate: 'Analysis order violation: order {n} ran before order {m}. Ensure ascending order.',
  warheadTemplate: [
    '# IL14 Violation: Analysis Order Misconfiguration',
    '',
    '## What Happened',
    'Higher-order analysis ran before lower-order completed.',
    '',
    '## How to Fix',
    'Configure GATE_ANALYSIS_ROUTING to run orders in ascending sequence.',
    '',
    '## Reference',
    'IL14 — Analysis Order Matters — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'order-correct', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'guide',
  layer: 3,
  links: ['AO0-PASS-THROUGH', 'AO2-AST-WALKER', 'AO3-TYPECHECKER'],
  selfVerified: true,
};

export const IL15_EVIDENCE_TRIPLE_RULE: KnowledgeNode = {
  id: 'IL15-EVIDENCE-TRIPLE-RULE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL15',
  rule: [
    'EVIDENCE TRIPLE RULE: Every claim requires triple evidence — filesystem, test, and analysis.',
    'Component 1: FILESYSTEM DIFF — Merkle tree before/after snapshot comparison.',
    'Component 2: TEST EXECUTION — Run tests before/after, compare pass rates.',
    'Component 3: RGE SCORING — Run RGE before/after, compare violation counts.',
    'The agent cannot rephrase reality. The filesystem either changed or it did not.',
    'All three components must improve (or at least not regress) for evidence to be valid.',
    'A single component is not enough — the triple provides cross-validation.',
  ].join('\n'),
  detectionMethod: 'For every gate advance, verify three evidence components exist: filesystem diff, test result, RGE score.',
  fixTemplate: 'Before advancing any gate: (1) snapshot filesystem, (2) run tests, (3) run RGE. Compare before/after.',
  conditions: [
    { field: 'gate', op: 'in', value: ['VERIFY', 'TEST', 'AUDIT', 'DELIVERY'] },
  ],
  bulletTemplate: 'Evidence incomplete for gate {gate}: need filesystem + test + RGE triple.',
  warheadTemplate: [
    '# IL15 Violation: Evidence Not Triple',
    '',
    '## What Happened',
    'Gate advance was attempted without all three evidence components.',
    '',
    '## How to Fix',
    'Produce: (1) filesystem Merkle diff, (2) test results, (3) RGE score. All three required.',
    '',
    '## Reference',
    'IL15 — Evidence Triple Rule — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'evidence-triple', verify: 'gate-chain', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['IL01-OUTPUT-IS-REALITY', 'IL10-EVIDENCE-IS-MECHANICAL', 'R22-CLAIM-REALITY'],
  selfVerified: true,
};

export const IL16_DERAILMENT_FIVE_SIGNALS: KnowledgeNode = {
  id: 'IL16-DERAILMENT-FIVE-SIGNALS',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL16',
  rule: [
    'DERAILMENT FIVE SIGNALS: Detect when the agent has lost focus on the task.',
    'Signal 1: Modifying files not in scope.',
    'Signal 2: Making unnecessary changes beyond the task.',
    'Signal 3: Extended exploration without convergence toward the goal.',
    'Signal 4: Referencing concepts not in the task description.',
    'Signal 5: Producing output significantly longer than required.',
    'Recovery: Stop → Revert → Re-state task → Resume from last good state.',
    'Derailment compounds — the longer it goes undetected, the harder the recovery.',
  ].join('\n'),
  detectionMethod: 'Monitor file modifications against task scope. Track exploration time without convergence. Compare output length to task requirements. Detect references to out-of-scope concepts.',
  fixTemplate: 'On derailment detection: (1) Stop all work, (2) Revert to last checkpoint, (3) Re-state the task, (4) Resume from the last good state.',
  conditions: [
    { field: 'driftLevel', op: 'matches', value: 'high' },
  ],
  bulletTemplate: 'Derailment signal {n}: {description}. Stop, revert, re-state task.',
  warheadTemplate: [
    '# IL16 Violation: Derailment Detected',
    '',
    '## What Happened',
    'The agent has exhibited one or more derailment signals.',
    '',
    '## How to Fix',
    '1. Stop all current work.',
    '2. Revert to the last checkpoint.',
    '3. Re-state the original task.',
    '4. Resume from the last known good state.',
    '',
    '## Reference',
    'IL16 — Derailment Five Signals — T3 §17',
  ].join('\n'),
  evidenceSpec: { id: 'no-derailment', verify: 'claim-reality', minQuality: 0.90 },
  severity: 'block',
  layer: 5,
  links: ['CME-T4-DRIFT-DETECTION', 'AP-SCOPE-CREEP'],
  selfVerified: true,
};

export const IL17_ESCALATION_CUMULATIVE: KnowledgeNode = {
  id: 'IL17-ESCALATION-CUMULATIVE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL17',
  rule: [
    'ESCALATION IS CUMULATIVE: Violation tracking accumulates across the session.',
    'Escalation protocol: WARN → BLOCK → RESTART → LOCKOUT.',
    'Tracking never resets to zero within a session.',
    'Violations decay over time — recent violations weigh more than old ones.',
    'First LOW severity → INFORM. First MEDIUM → WARN. First HIGH → BLOCK. First CRITICAL → REVERT.',
    'Second same severity → escalate one level.',
    'This prevents the agent from "forgetting" its history of violations.',
  ].join('\n'),
  detectionMethod: 'Track violation count and severity per session. Apply decay function. Compute current escalation level.',
  fixTemplate: 'Implement cumulative tracking with decay. Map (severity, count) to escalation action.',
  conditions: [
    { field: 'phase', op: 'equals', value: 'post-execution' },
  ],
  bulletTemplate: 'Escalation: {level} reached after {count} violations. Current action: {action}.',
  warheadTemplate: [
    '# IL17: Escalation Level {level}',
    '',
    '## What Happened',
    'Cumulative violations have reached escalation level {level}.',
    '',
    '## Protocol',
    'WARN → BLOCK → RESTART → LOCKOUT',
    '',
    '## Reference',
    'IL17 — Escalation Is Cumulative — T3 §18',
  ].join('\n'),
  evidenceSpec: { id: 'escalation-tracked', verify: 'fs-check', minQuality: 0.90 },
  severity: 'warn',
  layer: 5,
  links: ['AP-REPEATED-VIOLATION', 'ENF-ESCALATION'],
  selfVerified: true,
};

export const IL18_THEATRICAL_CODE_ZERO: KnowledgeNode = {
  id: 'IL18-THEATRICAL-CODE-ZERO',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL18',
  rule: [
    'THEATRICAL CODE ZERO TOLERANCE: No code that pretends to work.',
    'A function that returns a positive flag without performing side effects is theatrical.',
    'A function that returns a file path without writing the file is theatrical.',
    'A test that asserts a hardcoded literal is theatrical (fake test).',
    'A mock/stub in production code is theatrical.',
    'An enforcement function that never blocks is theatrical.',
    'Zero tolerance. Every theatrical code instance is a CRITICAL violation. No exceptions.',
  ].join('\n'),
  detectionMethod: 'SRE audit: detect theatrical returns (success flag without side effects), fake tests (hardcoded literals in expect), mocks in production, enforcement functions that never fail.',
  fixTemplate: 'Remove theatrical code. Either perform the real work or return action_required with instructions.',
  conditions: [
    { field: 'gate', op: 'in', value: ['BUILD', 'VERIFY', 'TEST', 'AUDIT'] },
  ],
  bulletTemplate: 'Theatrical code at line {line}: {pattern}. Perform real work or return action_required.',
  warheadTemplate: [
    '# IL18 Violation: Theatrical Code',
    '',
    '## What Happened',
    'Code was detected that pretends to work without performing actual side effects.',
    '',
    '## How to Fix',
    'Either perform the real work (write the file, call the API, run the test)',
    'or return action_required with exact instructions.',
    '',
    '## Reference',
    'IL18 — Theatrical Code Zero Tolerance — T3 §11',
  ].join('\n'),
  evidenceSpec: { id: 'no-theatrical', verify: 'sre-audit', minQuality: 0.99 },
  severity: 'block',
  layer: 4,
  links: ['P11-OUTPUT-IS-THE-WORK', 'SRE-S1-THEATRICAL-RETURN', 'AP-FAKE-TEST'],
  selfVerified: true,
};

export const IL19_GATE_ORDER_IMMUTABLE: KnowledgeNode = {
  id: 'IL19-GATE-ORDER-IMMUTABLE',
  source: 'rg-standards',
  sourceFile: 'RUNTIME_GRADE_BIBLE.md',
  category: 'iron-law',
  ironLaw: 'IL19',
  rule: [
    'GATE ORDER IS IMMUTABLE: PLAN → BUILD → VERIFY → TEST → AUDIT → DELIVERY.',
    'No gate may be skipped. No gate may be reordered.',
    'VERIFY (type safety, compilation) comes BEFORE TEST (runtime container testing).',
    'Each gate requires specific evidence from the previous gate.',
    'Gate advancement is mechanical — evidence must exist and pass verification.',
    'The agent cannot self-advance gates. The gate engine controls all transitions.',
    'Skipping a gate means skipping verification — that is a CRITICAL violation.',
  ].join('\n'),
  detectionMethod: 'Verify gate transitions follow the immutable order. Check that each gate has required evidence from the previous gate.',
  fixTemplate: 'Follow the gate chain exactly. Produce required evidence for each gate. Let the gate engine control transitions.',
  conditions: [
    { field: 'gateTransition', op: 'exists', value: true },
  ],
  bulletTemplate: 'Gate order violation: attempting to skip {gate} or reorder. Follow PLAN→BUILD→VERIFY→TEST→AUDIT→DELIVERY.',
  warheadTemplate: [
    '# IL19 Violation: Gate Order Violation',
    '',
    '## What Happened',
    'A gate transition was attempted that violates the immutable order.',
    '',
    '## How to Fix',
    'Follow the chain: PLAN → BUILD → VERIFY → TEST → AUDIT → DELIVERY.',
    'No skips. No reorders. Produce evidence for each gate.',
    '',
    '## Reference',
    'IL19 — Gate Order Is Immutable — RGB',
  ].join('\n'),
  evidenceSpec: { id: 'gate-chain', verify: 'gate-chain', minQuality: 0.99 },
  severity: 'block',
  layer: 5,
  links: ['GR-PLAN', 'GR-BUILD', 'GR-VERIFY', 'GR-TEST', 'GR-AUDIT', 'GR-DELIVERY'],
  selfVerified: true,
};

export const IL20_COMPACTION_PRESERVES_STATE: KnowledgeNode = {
  id: 'IL20-COMPACTION-PRESERVES-STATE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL20',
  rule: [
    'COMPACTION PRESERVES STATE: Context compaction must not lose critical state.',
    'Before compaction: serialize all gate states, evidence IDs, checkpoint data.',
    'After compaction: restore all serialized state. Verify nothing was lost.',
    'Compaction is a risk event — it can cause the agent to "forget" where it is.',
    'The warhead system injects recovery knowledge after compaction (remembering duty).',
    'Critical state: current gate, registered evidence, iteration count, violation history.',
    'If state is lost after compaction, the agent must re-derive it from the filesystem.',
  ].join('\n'),
  detectionMethod: 'Before/after compaction: compare state snapshot. Verify gate, evidence, checkpoint data preserved.',
  fixTemplate: 'Implement compacting hook: serialize state before, restore after. Inject warhead with current gate + recent events.',
  conditions: [
    { field: 'phase', op: 'equals', value: 'gate-evaluation' },
  ],
  bulletTemplate: 'Compaction state loss detected. Re-derive from .shark/ checkpoint files.',
  warheadTemplate: [
    '# IL20: Compaction Recovery',
    '',
    '## What Happened',
    'Context compaction occurred. State must be preserved and restored.',
    '',
    '## How to Recover',
    '1. Read .shark/gate-state.json for current gate.',
    '2. Read .shark/evidence/ for registered evidence.',
    '3. Read .shark/checkpoint for last good state.',
    '4. Inject warhead with current position and recent events.',
    '',
    '## Reference',
    'IL20 — Compaction Preserves State — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'state-preserved', verify: 'fs-check', minQuality: 0.95 },
  severity: 'block',
  layer: 5,
  links: ['ENF-COMPACTION-HOOK', 'WARHEAD-REMEMBERING'],
  selfVerified: true,
};

export const IL21_BULLET_BEFORE_THROW: KnowledgeNode = {
  id: 'IL21-BULLET-BEFORE-THROW',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL21',
  rule: [
    'BULLET BEFORE THROW: Guidance bullets must be pushed BEFORE the enforcement throw.',
    'After a throw, the model only reads ~80 characters of context.',
    'If the bullet is after the throw, the model never sees it.',
    'Bullets are <80 characters: contextually precise (line number, function name, specific fix).',
    'Push bullets as separate output.message calls BEFORE throw.',
    'The bullet tells the model exactly what to fix and how — in one line.',
    'Without bullets, the model has no guidance and repeats the same mistake.',
  ].join('\n'),
  detectionMethod: 'Verify that bullet guidance is pushed via output.message BEFORE every enforcement throw. Check bullet length <80 chars.',
  fixTemplate: 'Before every throw: messenger.push({ type: "bullet", text: bullet }). Then throw. The bullet must be <80 chars.',
  conditions: [
    { field: 'phase', op: 'equals', value: 'pre-execution' },
  ],
  bulletTemplate: 'Bullet missing before throw at {site}. Push guidance BEFORE throw.',
  warheadTemplate: [
    '# IL21: Bullet Missing Before Throw',
    '',
    '## What Happened',
    'An enforcement throw occurred without preceding bullet guidance.',
    '',
    '## How to Fix',
    'Push a <80 char bullet via output.message BEFORE every throw.',
    '',
    '## Reference',
    'IL21 — Bullet Before Throw — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'bullet-before-throw', verify: 'rge-audit', minQuality: 0.90 },
  severity: 'warn',
  layer: 4,
  links: ['ENF-BULLET-SYSTEM', 'BULLET-GENERATOR'],
  selfVerified: true,
};

export const IL22_PROGRESSIVE_DISCLOSURE: KnowledgeNode = {
  id: 'IL22-PROGRESSIVE-DISCLOSURE',
  source: 'alg-sys',
  sourceFile: 'T3_ALGORITHMIC_SYSTEMS.md',
  category: 'iron-law',
  ironLaw: 'IL22',
  rule: [
    'PROGRESSIVE DISCLOSURE: Only inject NEW knowledge the model hasn\'t already been told.',
    'Track what the model has already received per session.',
    'When a knowledge node matches, check if it was already disclosed.',
    'If already disclosed, skip injection — don\'t waste context budget.',
    'If not disclosed, inject and mark as disclosed.',
    'This prevents the same guidance from being repeated 10 times.',
    'Progressive disclosure maximizes the value of each token of context.',
  ].join('\n'),
  detectionMethod: 'Track disclosed knowledge node IDs per session. Before injection, check if already disclosed.',
  fixTemplate: 'Maintain a Set<string> of disclosed node IDs. Before injecting, check membership. After injecting, add to set.',
  conditions: [
    { field: 'phase', op: 'equals', value: 'pre-execution' },
  ],
  bulletTemplate: 'Knowledge {id} already disclosed this session. Skipping injection.',
  warheadTemplate: [
    '# IL22: Progressive Disclosure',
    '',
    '## Principle',
    'Only inject knowledge the model has NOT already received this session.',
    'Track disclosed IDs. Skip repeats. Maximize context budget value.',
    '',
    '## Reference',
    'IL22 — Progressive Disclosure — T3 §1',
  ].join('\n'),
  evidenceSpec: { id: 'disclosure-tracked', verify: 'fs-check', minQuality: 0.90 },
  severity: 'guide',
  layer: 3,
  links: ['ENF-CONTEXT-MATCHER', 'WARHEAD-ORIENTING'],
  selfVerified: true,
};

// EXPORTS
export const ironLaws: KnowledgeNode[] = [
  IL01_OUTPUT_IS_REALITY,
  IL02_CONTRACT_HONORED,
  IL03_ASYNC_COMPLETENESS,
  IL04_NO_SILENT_FAILURE,
  IL05_ATOMIC_TRANSITION,
  IL06_RESOURCE_OWNERSHIP,
  IL07_ENVIRONMENT_INDEPENDENCE,
  IL08_FAIL_FAST_CONFIG,
  IL09_WIRE_DONT_DECLARE,
  IL10_EVIDENCE_IS_MECHANICAL,
  IL11_OUTPUT_IS_PROOF,
  IL12_EMPTY_IS_NOT_SUCCESS,
  IL13_RULE_OWNERSHIP_EXCLUSIVE,
  IL14_ANALYSIS_ORDER_MATTERS,
  IL15_EVIDENCE_TRIPLE_RULE,
  IL16_DERAILMENT_FIVE_SIGNALS,
  IL17_ESCALATION_CUMULATIVE,
  IL18_THEATRICAL_CODE_ZERO,
  IL19_GATE_ORDER_IMMUTABLE,
  IL20_COMPACTION_PRESERVES_STATE,
  IL21_BULLET_BEFORE_THROW,
  IL22_PROGRESSIVE_DISCLOSURE,
];
